// Country-specific demo data for all 39 supported countries
// Each country has success and failure scenarios with localized data

export interface DemoData {
  firstName: string;
  middleName: string;
  lastName: string;
  email: string;
  phone: string;
  dob: string;
  gender: string;
  idNumber: string;
  address: string;
  city: string;
  idType: string;
  verificationScore: number;
  riskLevel: 'low' | 'medium' | 'high';
  failureReasons?: {
    documentAuth: { status: 'passed' | 'failed' | 'warning'; detail: string };
    faceMatch: { status: 'passed' | 'failed' | 'warning'; detail: string };
    livenessCheck: { status: 'passed' | 'failed' | 'warning'; detail: string };
    dataConsistency: { status: 'passed' | 'failed' | 'warning'; detail: string };
  };
}

type CountryDemoData = {
  success: DemoData;
  failure: DemoData;
};

export const countryDemoData: Record<string, CountryDemoData> = {
  // Argentina
  AR: {
    success: {
      firstName: 'Santiago',
      middleName: 'Matías',
      lastName: 'García',
      email: 'santiago.garcia@gmail.com',
      phone: '+54 11 4567 8901',
      dob: '1988-07-22',
      gender: 'male',
      idNumber: '28.456.789',
      address: 'Av. Corrientes 1234, Piso 5',
      city: 'Buenos Aires',
      idType: 'DNI',
      verificationScore: 97.8,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Carlos',
      middleName: '',
      lastName: 'Rodriguez',
      email: 'carlos_temp123@mailinator.com',
      phone: '+54 00 0000 0000',
      dob: '1990-01-01',
      gender: 'male',
      idNumber: '00.000.000',
      address: 'Calle Falsa 123',
      city: 'CABA',
      idType: 'DNI',
      verificationScore: 24.5,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'DNI hologram not detected, document may be counterfeit' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 18% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Potential photo of a photo detected' },
        dataConsistency: { status: 'failed', detail: 'Invalid CUIL format, disposable email provider detected' },
      },
    },
  },

  // Australia
  AU: {
    success: {
      firstName: 'Sample',
      middleName: '',
      lastName: 'Specimen',
      email: 'sample.specimen@outlook.com.au',
      phone: '+61 2 9876 5432',
      dob: '1991-03-18',
      gender: 'male',
      idNumber: '02345678',
      address: 'Peel St 1',
      city: 'Sydney',
      idType: "Driver's Licence",
      verificationScore: 98.2,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Michael',
      middleName: '',
      lastName: 'Smith',
      email: 'mike.smith.test@tempmail.com',
      phone: '+61 0 0000 0000',
      dob: '1995-06-15',
      gender: 'male',
      idNumber: 'XX0000000',
      address: '1 Test Road',
      city: 'Sydney',
      idType: 'Driver Licence',
      verificationScore: 31.2,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'Driver licence expiry date inconsistent with issue date' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 29% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Insufficient lighting for reliable liveness detection' },
        dataConsistency: { status: 'failed', detail: 'Address not found in Australian postal database' },
      },
    },
  },

  // Austria
  AT: {
    success: {
      firstName: 'Maximilian',
      middleName: 'Johann',
      lastName: 'Müller',
      email: 'maximilian.mueller@gmx.at',
      phone: '+43 1 234 5678',
      dob: '1982-04-30',
      gender: 'male',
      idNumber: '123456789',
      address: 'Kärntner Straße 51',
      city: 'Wien',
      idType: 'Personalausweis',
      verificationScore: 96.9,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Hans',
      middleName: '',
      lastName: 'Schmidt',
      email: 'hans.test@fakemail.at',
      phone: '+43 0 000 0000',
      dob: '1970-01-01',
      gender: 'male',
      idNumber: '000000000',
      address: 'Teststraße 1',
      city: 'Vienna',
      idType: 'Personalausweis',
      verificationScore: 28.4,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'Security watermark missing from ID card' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 22% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Static image detected, no movement' },
        dataConsistency: { status: 'failed', detail: 'ID number format invalid for Austrian documents' },
      },
    },
  },

  // Belgium
  BE: {
    success: {
      firstName: 'Lucas',
      middleName: 'Pierre',
      lastName: 'Dubois',
      email: 'lucas.dubois@skynet.be',
      phone: '+32 2 345 6789',
      dob: '1990-08-17',
      gender: 'male',
      idNumber: '90.08.17-123.45',
      address: 'Rue de la Loi 42',
      city: 'Bruxelles',
      idType: 'eID Card',
      verificationScore: 97.1,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Jean',
      middleName: '',
      lastName: 'Martin',
      email: 'jean.fake@tempmail.be',
      phone: '+32 0 000 0000',
      dob: '1985-12-25',
      gender: 'male',
      idNumber: '00.00.00-000.00',
      address: 'Fake Street 1',
      city: 'Brussels',
      idType: 'eID Card',
      verificationScore: 19.8,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'eID chip data could not be verified' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 15% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Replay attack suspected' },
        dataConsistency: { status: 'failed', detail: 'National register number checksum invalid' },
      },
    },
  },

  // Brazil
  BR: {
    success: {
      firstName: 'Gabriel',
      middleName: 'Silva',
      lastName: 'Santos',
      email: 'gabriel.santos@uol.com.br',
      phone: '+55 11 98765 4321',
      dob: '1992-03-08',
      gender: 'male',
      idNumber: '123.456.789-00',
      address: 'Av. Paulista 1578, Apt 121',
      city: 'São Paulo',
      idType: 'CPF',
      verificationScore: 98.5,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'João',
      middleName: '',
      lastName: 'Pereira',
      email: 'joao.test@fakeemail.br',
      phone: '+55 00 00000 0000',
      dob: '1980-05-20',
      gender: 'male',
      idNumber: '000.000.000-00',
      address: 'Rua Teste 123',
      city: 'Rio de Janeiro',
      idType: 'CPF',
      verificationScore: 22.3,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'CPF document shows signs of digital manipulation' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 21% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Low confidence in liveness detection' },
        dataConsistency: { status: 'failed', detail: 'CPF checksum validation failed, number is invalid' },
      },
    },
  },

  // Cambodia
  KH: {
    success: {
      firstName: 'Sokha',
      middleName: '',
      lastName: 'Chea',
      email: 'sokha.chea@gmail.com',
      phone: '+855 12 345 678',
      dob: '1994-12-05',
      gender: 'male',
      idNumber: '012345678',
      address: 'Street 63, Sangkat Boeung Keng Kang',
      city: 'Phnom Penh',
      idType: 'National ID',
      verificationScore: 95.4,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Dara',
      middleName: '',
      lastName: 'Sok',
      email: 'dara.temp@mailinator.com',
      phone: '+855 00 000 000',
      dob: '1990-01-01',
      gender: 'male',
      idNumber: '000000000',
      address: 'Unknown Street',
      city: 'Siem Reap',
      idType: 'National ID',
      verificationScore: 27.6,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card appears to be an older invalidated version' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 25% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Camera quality insufficient for reliable analysis' },
        dataConsistency: { status: 'failed', detail: 'ID number not found in government registry' },
      },
    },
  },

  // Canada
  CA: {
    success: {
      firstName: 'William',
      middleName: 'Robert',
      lastName: 'Thompson',
      email: 'william.thompson@rogers.com',
      phone: '+1 416 555 0123',
      dob: '1987-09-23',
      gender: 'male',
      idNumber: 'AB1234567',
      address: '100 Queen Street West, Suite 500',
      city: 'Toronto',
      idType: 'Passport',
      verificationScore: 98.9,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'David',
      middleName: '',
      lastName: 'Wilson',
      email: 'david.wilson.fake@tempmail.ca',
      phone: '+1 000 000 0000',
      dob: '1975-03-10',
      gender: 'male',
      idNumber: 'XX0000000',
      address: '1 Fake Avenue',
      city: 'Vancouver',
      idType: "Driver's License",
      verificationScore: 33.1,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'Provincial driver\'s license security features not detected' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 28% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Possible screen reflection detected' },
        dataConsistency: { status: 'failed', detail: 'Postal code format invalid for provided province' },
      },
    },
  },

  // Chile
  CL: {
    success: {
      firstName: 'Sebastián',
      middleName: 'Andrés',
      lastName: 'Fernández',
      email: 'sebastian.fernandez@entel.cl',
      phone: '+56 9 8765 4321',
      dob: '1991-06-14',
      gender: 'male',
      idNumber: '12.345.678-9',
      address: 'Av. Providencia 1234, Of. 567',
      city: 'Santiago',
      idType: 'RUN',
      verificationScore: 97.3,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Pedro',
      middleName: '',
      lastName: 'González',
      email: 'pedro.test@fakemail.cl',
      phone: '+56 0 0000 0000',
      dob: '1988-08-08',
      gender: 'male',
      idNumber: '00.000.000-0',
      address: 'Calle Falsa 111',
      city: 'Valparaíso',
      idType: 'RUN',
      verificationScore: 26.7,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'RUN card chip data unreadable' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 24% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Static image detected' },
        dataConsistency: { status: 'failed', detail: 'RUN verification digit does not match' },
      },
    },
  },

  // China
  CN: {
    success: {
      firstName: 'Wei',
      middleName: '',
      lastName: 'Zhang',
      email: 'zhang.wei@163.com',
      phone: '+86 138 1234 5678',
      dob: '1989-10-01',
      gender: 'male',
      idNumber: '310101198910012345',
      address: '南京西路1266号',
      city: 'Shanghai',
      idType: 'Resident ID Card',
      verificationScore: 96.8,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Ming',
      middleName: '',
      lastName: 'Li',
      email: 'li.ming.test@tempmail.cn',
      phone: '+86 000 0000 0000',
      dob: '1985-05-05',
      gender: 'male',
      idNumber: '000000000000000000',
      address: '测试路123号',
      city: 'Beijing',
      idType: 'Resident ID Card',
      verificationScore: 29.4,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card region code does not match issuing authority' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 26% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Unable to verify with high confidence' },
        dataConsistency: { status: 'failed', detail: 'ID number checksum invalid, birth date does not match' },
      },
    },
  },

  // Czech Republic
  CZ: {
    success: {
      firstName: 'Jakub',
      middleName: 'Petr',
      lastName: 'Novák',
      email: 'jakub.novak@seznam.cz',
      phone: '+420 602 123 456',
      dob: '1993-02-28',
      gender: 'male',
      idNumber: '930228/1234',
      address: 'Václavské náměstí 12',
      city: 'Praha',
      idType: 'Občanský průkaz',
      verificationScore: 97.5,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Jan',
      middleName: '',
      lastName: 'Svoboda',
      email: 'jan.test@fakemail.cz',
      phone: '+420 000 000 000',
      dob: '1970-01-01',
      gender: 'male',
      idNumber: '000000/0000',
      address: 'Testovací 1',
      city: 'Brno',
      idType: 'Občanský průkaz',
      verificationScore: 25.8,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card security hologram appears damaged or fake' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 23% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'No eye movement detected during check' },
        dataConsistency: { status: 'failed', detail: 'Birth number format invalid' },
      },
    },
  },

  // Denmark
  DK: {
    success: {
      firstName: 'Magnus',
      middleName: 'Erik',
      lastName: 'Jensen',
      email: 'magnus.jensen@mail.dk',
      phone: '+45 20 12 34 56',
      dob: '1986-07-19',
      gender: 'male',
      idNumber: '190786-1234',
      address: 'Strøget 45, 2. sal',
      city: 'København',
      idType: 'Sundhedskort',
      verificationScore: 98.1,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Lars',
      middleName: '',
      lastName: 'Nielsen',
      email: 'lars.fake@tempmail.dk',
      phone: '+45 00 00 00 00',
      dob: '1990-06-06',
      gender: 'male',
      idNumber: '000000-0000',
      address: 'Testvej 1',
      city: 'Aarhus',
      idType: 'Sundhedskort',
      verificationScore: 30.2,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'Health card barcode data inconsistent' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 27% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Borderline liveness confidence' },
        dataConsistency: { status: 'failed', detail: 'CPR number checksum validation failed' },
      },
    },
  },

  // Finland
  FI: {
    success: {
      firstName: 'Mikko',
      middleName: 'Juhani',
      lastName: 'Virtanen',
      email: 'mikko.virtanen@helsinki.fi',
      phone: '+358 40 123 4567',
      dob: '1984-12-06',
      gender: 'male',
      idNumber: '061284-123A',
      address: 'Mannerheimintie 10 A 5',
      city: 'Helsinki',
      idType: 'Henkilökortti',
      verificationScore: 97.9,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Antti',
      middleName: '',
      lastName: 'Korhonen',
      email: 'antti.test@fakemail.fi',
      phone: '+358 00 000 0000',
      dob: '1975-04-04',
      gender: 'male',
      idNumber: '000000-000A',
      address: 'Testikatu 1',
      city: 'Tampere',
      idType: 'Henkilökortti',
      verificationScore: 28.6,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card MRZ data does not match visible text' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 25% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Suspected presentation attack' },
        dataConsistency: { status: 'failed', detail: 'Personal identity code format invalid' },
      },
    },
  },

  // France
  FR: {
    success: {
      firstName: 'Antoine',
      middleName: 'Louis',
      lastName: 'Bernard',
      email: 'antoine.bernard@orange.fr',
      phone: '+33 6 12 34 56 78',
      dob: '1988-05-14',
      gender: 'male',
      idNumber: '880514123456789',
      address: '25 Avenue des Champs-Élysées',
      city: 'Paris',
      idType: "Carte Nationale d'Identité",
      verificationScore: 98.4,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Pierre',
      middleName: '',
      lastName: 'Dupont',
      email: 'pierre.fake@tempmail.fr',
      phone: '+33 0 00 00 00 00',
      dob: '1980-02-02',
      gender: 'male',
      idNumber: '000000000000000',
      address: 'Rue du Test 1',
      city: 'Lyon',
      idType: "Carte Nationale d'Identité",
      verificationScore: 23.7,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'CNI optical security features not detected' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 19% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Video injection attack suspected' },
        dataConsistency: { status: 'failed', detail: 'INSEE number validation failed' },
      },
    },
  },

  // Germany
  DE: {
    success: {
      firstName: 'Erika',
      middleName: '',
      lastName: 'Mustermann',
      email: 'erika.mustermann@t-online.de',
      phone: '+49 30 12345678',
      dob: '1983-08-12',
      gender: 'female',
      idNumber: 'LZ6311T47',
      address: 'Heidestraße 17',
      city: 'Köln',
      idType: 'Personalausweis',
      verificationScore: 98.6,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Thomas',
      middleName: '',
      lastName: 'Becker',
      email: 'thomas.test@fakemail.de',
      phone: '+49 00 00000000',
      dob: '1965-07-07',
      gender: 'male',
      idNumber: '000000000',
      address: 'Teststraße 1',
      city: 'München',
      idType: 'Personalausweis',
      verificationScore: 26.9,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'Personalausweis NFC chip authentication failed' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 24% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Low confidence in depth detection' },
        dataConsistency: { status: 'failed', detail: 'ID number format does not match German standards' },
      },
    },
  },

  // Greece
  GR: {
    success: {
      firstName: 'Nikolaos',
      middleName: 'Georgios',
      lastName: 'Papadopoulos',
      email: 'nikolaos.papadopoulos@otenet.gr',
      phone: '+30 210 123 4567',
      dob: '1987-08-15',
      gender: 'male',
      idNumber: 'ΑΒ123456',
      address: 'Οδός Ερμού 42',
      city: 'Αθήνα',
      idType: 'Ταυτότητα',
      verificationScore: 96.7,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Dimitrios',
      middleName: '',
      lastName: 'Konstantinou',
      email: 'dimitris.fake@tempmail.gr',
      phone: '+30 000 000 0000',
      dob: '1978-09-09',
      gender: 'male',
      idNumber: 'ΧΧ000000',
      address: 'Δοκιμαστική 1',
      city: 'Thessaloniki',
      idType: 'Ταυτότητα',
      verificationScore: 27.3,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card appears to be from an outdated series' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 23% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Printed photo detected' },
        dataConsistency: { status: 'failed', detail: 'AFM tax number could not be verified' },
      },
    },
  },

  // Hong Kong
  HK: {
    success: {
      firstName: 'Chi Wai',
      middleName: '',
      lastName: 'Chan',
      email: 'chiwai.chan@netvigator.com',
      phone: '+852 9123 4567',
      dob: '1985-04-08',
      gender: 'male',
      idNumber: 'A123456(7)',
      address: '88 Queensway, Admiralty',
      city: 'Hong Kong',
      idType: 'HKID',
      verificationScore: 97.8,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Siu Ming',
      middleName: '',
      lastName: 'Wong',
      email: 'wong.test@fakemail.hk',
      phone: '+852 0000 0000',
      dob: '1992-02-02',
      gender: 'male',
      idNumber: 'X000000(0)',
      address: 'Test Road 1',
      city: 'Kowloon',
      idType: 'HKID',
      verificationScore: 32.1,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'HKID smart card chip unresponsive' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 30% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Insufficient frames for reliable analysis' },
        dataConsistency: { status: 'failed', detail: 'HKID check digit validation failed' },
      },
    },
  },

  // Indonesia
  ID: {
    success: {
      firstName: 'Budi',
      middleName: 'Santoso',
      lastName: 'Wijaya',
      email: 'budi.wijaya@gmail.com',
      phone: '+62 812 3456 7890',
      dob: '1991-01-17',
      gender: 'male',
      idNumber: '3171011701910001',
      address: 'Jl. Sudirman No. 52',
      city: 'Jakarta',
      idType: 'KTP',
      verificationScore: 96.5,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Agus',
      middleName: '',
      lastName: 'Setiawan',
      email: 'agus.temp@mailinator.com',
      phone: '+62 000 0000 0000',
      dob: '1988-08-08',
      gender: 'male',
      idNumber: '0000000000000000',
      address: 'Jl. Test 1',
      city: 'Surabaya',
      idType: 'KTP',
      verificationScore: 25.4,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'KTP-el chip data cannot be read' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 22% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Suspected mask or face covering' },
        dataConsistency: { status: 'failed', detail: 'NIK region code invalid' },
      },
    },
  },

  // India
  IN: {
    success: {
      firstName: 'Rajesh',
      middleName: 'Kumar',
      lastName: 'Sharma',
      email: 'rajesh.sharma@rediffmail.com',
      phone: '+91 98765 43210',
      dob: '1986-11-26',
      gender: 'male',
      idNumber: '1234 5678 9012',
      address: '42, MG Road, Connaught Place',
      city: 'New Delhi',
      idType: 'Aadhaar',
      verificationScore: 97.4,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Amit',
      middleName: '',
      lastName: 'Patel',
      email: 'amit.fake@tempmail.in',
      phone: '+91 00000 00000',
      dob: '1990-01-26',
      gender: 'male',
      idNumber: '0000 0000 0000',
      address: 'Test Nagar 1',
      city: 'Mumbai',
      idType: 'Aadhaar',
      verificationScore: 24.8,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'Aadhaar QR code data mismatch with printed details' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 21% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Glasses reflection interfering with eye tracking' },
        dataConsistency: { status: 'failed', detail: 'Aadhaar Verhoeff checksum invalid' },
      },
    },
  },

  // Italy
  IT: {
    success: {
      firstName: 'Marco',
      middleName: 'Antonio',
      lastName: 'Rossi',
      email: 'marco.rossi@libero.it',
      phone: '+39 02 1234 5678',
      dob: '1989-04-25',
      gender: 'male',
      idNumber: 'CA12345AB',
      address: 'Via Roma 42',
      city: 'Milano',
      idType: "Carta d'Identità",
      verificationScore: 97.6,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Giuseppe',
      middleName: '',
      lastName: 'Bianchi',
      email: 'giuseppe.test@fakemail.it',
      phone: '+39 00 0000 0000',
      dob: '1972-06-06',
      gender: 'male',
      idNumber: 'XX00000XX',
      address: 'Via Test 1',
      city: 'Roma',
      idType: "Carta d'Identità",
      verificationScore: 28.2,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'CIE document shows signs of physical tampering' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 26% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'No depth information detected' },
        dataConsistency: { status: 'failed', detail: 'Codice Fiscale does not match provided data' },
      },
    },
  },

  // Kenya
  KE: {
    success: {
      firstName: 'James',
      middleName: 'Omondi',
      lastName: 'Kamau',
      email: 'james.kamau@safaricom.co.ke',
      phone: '+254 712 345 678',
      dob: '1993-12-12',
      gender: 'male',
      idNumber: '12345678',
      address: 'Kenyatta Avenue, Tower 5',
      city: 'Nairobi',
      idType: 'National ID',
      verificationScore: 96.2,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Peter',
      middleName: '',
      lastName: 'Mwangi',
      email: 'peter.temp@mailinator.com',
      phone: '+254 000 000 000',
      dob: '1985-05-05',
      gender: 'male',
      idNumber: '00000000',
      address: 'Test Street 1',
      city: 'Mombasa',
      idType: 'National ID',
      verificationScore: 26.5,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'National ID serial number format invalid' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 24% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Low light conditions affected analysis' },
        dataConsistency: { status: 'failed', detail: 'ID number not found in IPRS database' },
      },
    },
  },

  // Malaysia
  MY: {
    success: {
      firstName: 'Ahmad',
      middleName: 'Bin',
      lastName: 'Abdullah',
      email: 'ahmad.abdullah@tm.com.my',
      phone: '+60 12 345 6789',
      dob: '1988-08-31',
      gender: 'male',
      idNumber: '880831-14-5678',
      address: 'Jalan Bukit Bintang 42',
      city: 'Kuala Lumpur',
      idType: 'MyKad',
      verificationScore: 97.1,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Mohamed',
      middleName: '',
      lastName: 'Hassan',
      email: 'mohamed.fake@tempmail.my',
      phone: '+60 00 000 0000',
      dob: '1990-01-01',
      gender: 'male',
      idNumber: '000000-00-0000',
      address: 'Jalan Test 1',
      city: 'Penang',
      idType: 'MyKad',
      verificationScore: 29.7,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'MyKad chip authentication failed' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 27% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Suspected deepfake video' },
        dataConsistency: { status: 'failed', detail: 'IC number state code invalid' },
      },
    },
  },

  // Mexico
  MX: {
    success: {
      firstName: 'Carlos',
      middleName: 'Eduardo',
      lastName: 'Hernández',
      email: 'carlos.hernandez@prodigy.net.mx',
      phone: '+52 55 1234 5678',
      dob: '1987-09-16',
      gender: 'male',
      idNumber: 'HECA870916HDFRRL09',
      address: 'Av. Reforma 222, Col. Juárez',
      city: 'Ciudad de México',
      idType: 'INE',
      verificationScore: 97.8,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Juan',
      middleName: '',
      lastName: 'García',
      email: 'juan.test@fakemail.mx',
      phone: '+52 00 0000 0000',
      dob: '1980-05-05',
      gender: 'male',
      idNumber: 'XXXX000000XXXXXX00',
      address: 'Calle Test 1',
      city: 'Guadalajara',
      idType: 'INE',
      verificationScore: 25.3,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'INE holographic seal not authentic' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 22% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Photo of screen detected' },
        dataConsistency: { status: 'failed', detail: 'CURP validation algorithm failed' },
      },
    },
  },

  // Morocco
  MA: {
    success: {
      firstName: 'Youssef',
      middleName: '',
      lastName: 'El Amrani',
      email: 'youssef.amrani@menara.ma',
      phone: '+212 6 12 34 56 78',
      dob: '1990-07-30',
      gender: 'male',
      idNumber: 'BE123456',
      address: 'Boulevard Mohammed V, 45',
      city: 'Casablanca',
      idType: 'CNIE',
      verificationScore: 96.4,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Ahmed',
      middleName: '',
      lastName: 'Benali',
      email: 'ahmed.fake@tempmail.ma',
      phone: '+212 0 00 00 00 00',
      dob: '1985-03-03',
      gender: 'male',
      idNumber: 'XX000000',
      address: 'Rue Test 1',
      city: 'Rabat',
      idType: 'CNIE',
      verificationScore: 27.9,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'CNIE barcode data corrupted or fake' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 25% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Insufficient movement during capture' },
        dataConsistency: { status: 'failed', detail: 'CIN number format does not match regional codes' },
      },
    },
  },

  // Netherlands
  NL: {
    success: {
      firstName: 'Daan',
      middleName: 'Johannes',
      lastName: 'de Vries',
      email: 'daan.devries@xs4all.nl',
      phone: '+31 6 12345678',
      dob: '1989-04-27',
      gender: 'male',
      idNumber: 'SPECI2014',
      address: 'Damrak 1',
      city: 'Amsterdam',
      idType: 'Identiteitskaart',
      verificationScore: 98.3,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Jan',
      middleName: '',
      lastName: 'Jansen',
      email: 'jan.test@fakemail.nl',
      phone: '+31 0 00000000',
      dob: '1975-05-05',
      gender: 'male',
      idNumber: 'XXXXX0000',
      address: 'Teststraat 1',
      city: 'Rotterdam',
      idType: 'Identiteitskaart',
      verificationScore: 31.4,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card UV features not detected' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 28% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Camera angle suboptimal for analysis' },
        dataConsistency: { status: 'failed', detail: 'BSN elfproef checksum invalid' },
      },
    },
  },

  // New Zealand
  NZ: {
    success: {
      firstName: 'Specimen',
      middleName: '',
      lastName: 'Sample',
      email: 'specimen.sample@xtra.co.nz',
      phone: '+64 21 123 4567',
      dob: '1990-03-18',
      gender: 'male',
      idNumber: 'AB123456',
      address: 'Unit 1, 123 Street Address',
      city: 'Sample City',
      idType: 'Driver Licence',
      verificationScore: 98.0,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Jack',
      middleName: '',
      lastName: 'Brown',
      email: 'jack.fake@tempmail.nz',
      phone: '+64 00 000 0000',
      dob: '1988-08-08',
      gender: 'male',
      idNumber: 'XX000000',
      address: 'Test Road 1',
      city: 'Wellington',
      idType: "Driver's Licence",
      verificationScore: 30.6,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'Driver licence card material appears non-authentic' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 28% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Static image with no depth' },
        dataConsistency: { status: 'failed', detail: 'Licence number not found in NZTA database' },
      },
    },
  },

  // Nigeria
  NG: {
    success: {
      firstName: 'Chinedu',
      middleName: 'Emeka',
      lastName: 'Okafor',
      email: 'chinedu.okafor@gmail.com',
      phone: '+234 803 123 4567',
      dob: '1992-10-01',
      gender: 'male',
      idNumber: '12345678901',
      address: '15 Broad Street, Lagos Island',
      city: 'Lagos',
      idType: 'NIN',
      verificationScore: 95.8,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Emeka',
      middleName: '',
      lastName: 'Nwosu',
      email: 'emeka.temp@mailinator.com',
      phone: '+234 000 000 0000',
      dob: '1985-04-04',
      gender: 'male',
      idNumber: '00000000000',
      address: 'Test Street 1',
      city: 'Abuja',
      idType: 'NIN',
      verificationScore: 23.9,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'NIN slip appears to be a screenshot or photocopy' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 20% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Multiple faces detected in frame' },
        dataConsistency: { status: 'failed', detail: 'NIN not found in NIMC database' },
      },
    },
  },

  // Peru
  PE: {
    success: {
      firstName: 'José',
      middleName: 'Luis',
      lastName: 'Quispe',
      email: 'jose.quispe@gmail.com',
      phone: '+51 987 654 321',
      dob: '1988-07-28',
      gender: 'male',
      idNumber: '12345678',
      address: 'Av. Larco 345, Miraflores',
      city: 'Lima',
      idType: 'DNI',
      verificationScore: 96.9,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Miguel',
      middleName: '',
      lastName: 'Sánchez',
      email: 'miguel.fake@tempmail.pe',
      phone: '+51 000 000 000',
      dob: '1990-09-09',
      gender: 'male',
      idNumber: '00000000',
      address: 'Calle Test 1',
      city: 'Arequipa',
      idType: 'DNI',
      verificationScore: 26.2,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'DNI hologram not visible or fake' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 23% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Poor video quality' },
        dataConsistency: { status: 'failed', detail: 'DNI number not found in RENIEC database' },
      },
    },
  },

  // Philippines
  PH: {
    success: {
      firstName: 'Juan',
      middleName: 'Dela Cruz',
      lastName: 'Santos',
      email: 'juan.santos@globe.com.ph',
      phone: '+63 917 123 4567',
      dob: '1990-06-12',
      gender: 'male',
      idNumber: '1234-5678901-2',
      address: 'Ayala Avenue, Makati City',
      city: 'Manila',
      idType: 'PhilSys ID',
      verificationScore: 96.3,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Pedro',
      middleName: '',
      lastName: 'Reyes',
      email: 'pedro.test@fakemail.ph',
      phone: '+63 000 000 0000',
      dob: '1982-02-02',
      gender: 'male',
      idNumber: '0000-0000000-0',
      address: 'Test Street 1',
      city: 'Cebu',
      idType: 'PhilSys ID',
      verificationScore: 25.7,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'PhilSys ID QR code data invalid' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 22% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Face appears to be from a video recording' },
        dataConsistency: { status: 'failed', detail: 'PSN format validation failed' },
      },
    },
  },

  // Poland
  PL: {
    success: {
      firstName: 'Krzysztof',
      middleName: 'Piotr',
      lastName: 'Kowalski',
      email: 'krzysztof.kowalski@wp.pl',
      phone: '+48 601 234 567',
      dob: '1985-05-03',
      gender: 'male',
      idNumber: 'ABC123456',
      address: 'ul. Marszałkowska 42',
      city: 'Warszawa',
      idType: 'Dowód Osobisty',
      verificationScore: 97.7,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Adam',
      middleName: '',
      lastName: 'Nowak',
      email: 'adam.fake@tempmail.pl',
      phone: '+48 000 000 000',
      dob: '1970-10-10',
      gender: 'male',
      idNumber: 'XXX000000',
      address: 'ul. Testowa 1',
      city: 'Kraków',
      idType: 'Dowód Osobisty',
      verificationScore: 28.8,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card kinegram security feature missing' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 26% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'No blinking detected during capture' },
        dataConsistency: { status: 'failed', detail: 'PESEL checksum validation failed' },
      },
    },
  },

  // Singapore
  SG: {
    success: {
      firstName: 'Wei Ming',
      middleName: '',
      lastName: 'Tan',
      email: 'weiming.tan@singnet.com.sg',
      phone: '+65 9123 4567',
      dob: '1988-08-09',
      gender: 'male',
      idNumber: 'S8809091A',
      address: '1 Raffles Place, #20-01',
      city: 'Singapore',
      idType: 'NRIC',
      verificationScore: 98.7,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Ah Kow',
      middleName: '',
      lastName: 'Lim',
      email: 'ahkow.test@fakemail.sg',
      phone: '+65 0000 0000',
      dob: '1975-05-05',
      gender: 'male',
      idNumber: 'X0000000X',
      address: 'Test Road 1',
      city: 'Singapore',
      idType: 'NRIC',
      verificationScore: 32.5,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'NRIC card laser engraving anomalies detected' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 30% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Borderline liveness score' },
        dataConsistency: { status: 'failed', detail: 'NRIC checksum letter invalid' },
      },
    },
  },

  // Slovakia
  SK: {
    success: {
      firstName: 'Marek',
      middleName: 'Ján',
      lastName: 'Horváth',
      email: 'marek.horvath@azet.sk',
      phone: '+421 905 123 456',
      dob: '1991-11-17',
      gender: 'male',
      idNumber: '911117/1234',
      address: 'Obchodná 42',
      city: 'Bratislava',
      idType: 'Občiansky preukaz',
      verificationScore: 97.2,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Jozef',
      middleName: '',
      lastName: 'Kováč',
      email: 'jozef.fake@tempmail.sk',
      phone: '+421 000 000 000',
      dob: '1980-01-01',
      gender: 'male',
      idNumber: '000000/0000',
      address: 'Testová 1',
      city: 'Košice',
      idType: 'Občiansky preukaz',
      verificationScore: 27.1,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card microprint text unreadable' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 24% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Suspected printed mask' },
        dataConsistency: { status: 'failed', detail: 'Birth number control digits invalid' },
      },
    },
  },

  // South Africa
  ZA: {
    success: {
      firstName: 'Sipho',
      middleName: 'Thabo',
      lastName: 'Ndlovu',
      email: 'sipho.ndlovu@telkomsa.net',
      phone: '+27 82 123 4567',
      dob: '1989-12-16',
      gender: 'male',
      idNumber: '8912165012089',
      address: '123 Nelson Mandela Drive',
      city: 'Johannesburg',
      idType: 'Smart ID Card',
      verificationScore: 96.6,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'John',
      middleName: '',
      lastName: 'Dlamini',
      email: 'john.test@fakemail.za',
      phone: '+27 00 000 0000',
      dob: '1985-06-16',
      gender: 'male',
      idNumber: '0000000000000',
      address: 'Test Street 1',
      city: 'Cape Town',
      idType: 'Smart ID Card',
      verificationScore: 26.8,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'Smart ID card chip data corrupted' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 24% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Environmental lighting issues' },
        dataConsistency: { status: 'failed', detail: 'SA ID number Luhn checksum failed' },
      },
    },
  },

  // Spain
  ES: {
    success: {
      firstName: 'Alejandro',
      middleName: 'José',
      lastName: 'García',
      email: 'alejandro.garcia@telefonica.es',
      phone: '+34 612 345 678',
      dob: '1987-10-12',
      gender: 'male',
      idNumber: '12345678Z',
      address: 'Gran Vía 42, 3ºA',
      city: 'Madrid',
      idType: 'DNI',
      verificationScore: 98.1,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Manuel',
      middleName: '',
      lastName: 'López',
      email: 'manuel.fake@tempmail.es',
      phone: '+34 000 000 000',
      dob: '1975-04-04',
      gender: 'male',
      idNumber: '00000000X',
      address: 'Calle Test 1',
      city: 'Barcelona',
      idType: 'DNI',
      verificationScore: 29.3,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'DNI 3.0 chip authentication failed' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 27% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Screen artifacts detected in video' },
        dataConsistency: { status: 'failed', detail: 'NIF letter does not match number' },
      },
    },
  },

  // Sweden
  SE: {
    success: {
      firstName: 'Erik',
      middleName: 'Anders',
      lastName: 'Lindqvist',
      email: 'erik.lindqvist@telia.se',
      phone: '+46 70 123 4567',
      dob: '1986-06-06',
      gender: 'male',
      idNumber: '860606-1234',
      address: 'Drottninggatan 42',
      city: 'Stockholm',
      idType: 'Nationellt ID-kort',
      verificationScore: 98.4,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Anders',
      middleName: '',
      lastName: 'Svensson',
      email: 'anders.test@fakemail.se',
      phone: '+46 00 000 0000',
      dob: '1970-07-07',
      gender: 'male',
      idNumber: '000000-0000',
      address: 'Testgatan 1',
      city: 'Göteborg',
      idType: 'Nationellt ID-kort',
      verificationScore: 30.9,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card tactile features missing' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 28% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Inconsistent head movement pattern' },
        dataConsistency: { status: 'failed', detail: 'Personnummer Luhn check failed' },
      },
    },
  },

  // Switzerland
  CH: {
    success: {
      firstName: 'Lukas',
      middleName: 'Thomas',
      lastName: 'Müller',
      email: 'lukas.mueller@bluewin.ch',
      phone: '+41 79 123 45 67',
      dob: '1988-08-01',
      gender: 'male',
      idNumber: '756.1234.5678.90',
      address: 'Bahnhofstrasse 42',
      city: 'Zürich',
      idType: 'Identitätskarte',
      verificationScore: 98.8,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Peter',
      middleName: '',
      lastName: 'Schneider',
      email: 'peter.fake@tempmail.ch',
      phone: '+41 00 000 00 00',
      dob: '1972-02-02',
      gender: 'male',
      idNumber: '000.0000.0000.00',
      address: 'Teststrasse 1',
      city: 'Geneva',
      idType: 'Identitätskarte',
      verificationScore: 33.2,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'ID card intaglio printing quality inconsistent' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 31% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Lighting conditions variable' },
        dataConsistency: { status: 'failed', detail: 'AHV number EAN-13 checksum invalid' },
      },
    },
  },

  // Thailand
  TH: {
    success: {
      firstName: 'Somchai',
      middleName: '',
      lastName: 'Srisawat',
      email: 'somchai.srisawat@truemail.co.th',
      phone: '+66 81 234 5678',
      dob: '1990-12-05',
      gender: 'male',
      idNumber: '1-1234-56789-01-2',
      address: '42 Sukhumvit Road, Khlong Toei',
      city: 'Bangkok',
      idType: 'Thai ID Card',
      verificationScore: 96.8,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Prasert',
      middleName: '',
      lastName: 'Tanaka',
      email: 'prasert.test@fakemail.th',
      phone: '+66 00 000 0000',
      dob: '1985-05-05',
      gender: 'male',
      idNumber: '0-0000-00000-00-0',
      address: 'Test Soi 1',
      city: 'Chiang Mai',
      idType: 'Thai ID Card',
      verificationScore: 25.6,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'Thai ID laser perforation pattern incorrect' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 22% (threshold: 80%)' },
        livenessCheck: { status: 'failed', detail: 'Replay video attack detected' },
        dataConsistency: { status: 'failed', detail: 'Citizen ID checksum digit invalid' },
      },
    },
  },

  // United Kingdom
  GB: {
    success: {
      firstName: 'Sarah',
      middleName: 'Jane',
      lastName: 'Whitfield',
      email: 'sarah.whitfield@btinternet.com',
      phone: '+44 7700 900123',
      dob: '1990-03-18',
      gender: 'female',
      idNumber: 'MICRO753116SM9IJ',
      address: '122 Burns Crescent',
      city: 'Edinburgh',
      idType: 'Driving Licence',
      verificationScore: 98.5,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'James',
      middleName: '',
      lastName: 'Smith',
      email: 'james.fake@tempmail.co.uk',
      phone: '+44 0000 000000',
      dob: '1980-01-01',
      gender: 'male',
      idNumber: '000000000',
      address: 'Test Lane 1',
      city: 'Manchester',
      idType: 'Driving Licence',
      verificationScore: 31.7,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: 'UK driving licence hologram not authentic' },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 29% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Partial face occlusion detected' },
        dataConsistency: { status: 'failed', detail: 'NI number format invalid' },
      },
    },
  },

  // United States
  US: {
    success: {
      firstName: 'Ranjan',
      middleName: 'Rajesh',
      lastName: 'Reddy',
      email: 'ranjan.reddy@gmail.com',
      phone: '+1 415 555 0147',
      dob: '1981-03-07',
      gender: 'male',
      idNumber: 'Y4918848',
      address: '1601 Beach St 204',
      city: 'San Francisco',
      idType: 'Identification Card',
      verificationScore: 98.7,
      riskLevel: 'low',
    },
    failure: {
      firstName: 'Robert',
      middleName: '',
      lastName: 'Martinez',
      email: 'r.martinez_temp@mailinator.com',
      phone: '+1 000 000 0000',
      dob: '1990-01-01',
      gender: 'male',
      idNumber: '000-00-0000',
      address: '123 Fake Street',
      city: 'Anytown',
      idType: "Driver's License",
      verificationScore: 28.1,
      riskLevel: 'high',
      failureReasons: {
        documentAuth: { status: 'failed', detail: "State driver's license UV security features missing" },
        faceMatch: { status: 'failed', detail: 'Face match confidence: 25% (threshold: 80%)' },
        livenessCheck: { status: 'warning', detail: 'Unable to confirm liveness with high confidence' },
        dataConsistency: { status: 'failed', detail: 'SSN format invalid, disposable email detected' },
      },
    },
  },
};

// Helper function to get demo data by country and scenario
export function getDemoData(countryCode: string, scenario: 'success' | 'failure'): DemoData {
  const countryData = countryDemoData[countryCode];
  if (!countryData) {
    // Fallback to US if country not found
    return countryDemoData['US'][scenario];
  }
  return countryData[scenario];
}

// Get all supported country codes
export function getSupportedCountries(): string[] {
  return Object.keys(countryDemoData);
}
