"use client";

import { useState, useEffect, useCallback, Suspense } from "react";
import { useSearchParams } from "next/navigation";
import {
  Shield, LayoutDashboard, GitBranch, Users, AlertTriangle, FileText, List,
  LogOut, ChevronLeft, ChevronRight, ChevronDown, ChevronUp, Search,
  Activity, Globe, Clock, Eye, Smartphone, ShieldCheck, Zap,
  ArrowUpRight, ArrowDownRight, TrendingUp, Filter, Plus, Play, Download,
  CheckCircle, XCircle, AlertCircle, Timer, ArrowLeft,
  User, Lock, Mail, ExternalLink, Menu, X, Layers,
  Database, Code, RefreshCw, Hash, Copy, Flag,
  ArrowRight, MapPin, CreditCard, Phone, Calendar, Tag, Clipboard, Save
} from "lucide-react";

const BUREAU_LOGO="/bureau-logo.png";
const T={primary:"#253B80",primaryBg:"rgba(37,59,128,0.06)",navy900:"#0F1B3D",rose:"#E11D48",roseBg:"rgba(225,29,72,0.08)",amber:"#D97706",amberBg:"rgba(217,119,6,0.08)",emerald:"#059669",emeraldBg:"rgba(5,150,105,0.08)",blue:"#2563EB",blueBg:"rgba(37,99,235,0.08)",violet:"#7C3AED",violetBg:"rgba(124,58,237,0.08)",teal:"#0D9488",tealBg:"rgba(13,148,136,0.08)",orange:"#EA580C",orangeBg:"rgba(234,88,12,0.08)",bg:"#f8f9fb",white:"#fff",border:"#e5e7eb",borderLight:"#f3f4f6",t900:"#111827",t700:"#374151",t500:"#6b7280",t400:"#9ca3af",t300:"#d1d5db",mono:"'JetBrains Mono',ui-monospace,monospace",sans:"'DM Sans',ui-sans-serif,system-ui,sans-serif"};
function detectRegion(){try{const z=Intl.DateTimeFormat().resolvedOptions().timeZone||"";if(/Kolkata|Mumbai|Chennai|Delhi/.test(z))return"IN";if(/Singapore|Kuala_Lumpur|Jakarta|Bangkok|Manila/.test(z))return"SEA";return"US";}catch{return"US";}}
const regMap={US:{flag:"🇺🇸",country:"United States"},IN:{flag:"🇮🇳",country:"India"},SEA:{flag:"🇸🇬",country:"Singapore"}};

const dashAPIs=[{name:"ID Verification",calls:"1.2M",success:"99.2%",p50:"142ms",p99:"380ms",trend:"+12%"},{name:"Face Match",calls:"890K",success:"98.7%",p50:"210ms",p99:"520ms",trend:"+8%"},{name:"Document OCR",calls:"650K",success:"97.1%",p50:"340ms",p99:"890ms",trend:"+15%"},{name:"Liveness Check",calls:"720K",success:"99.5%",p50:"180ms",p99:"410ms",trend:"+22%"},{name:"AML Screening",calls:"430K",success:"99.8%",p50:"280ms",p99:"650ms",trend:"+5%"},{name:"Device Intel",calls:"2.1M",success:"99.9%",p50:"45ms",p99:"120ms",trend:"+34%"}];
const dashWF=[{name:"KYC Onboarding",exec:"145K",success:"94.2%",rejected:"3.1%",manual:"2.7%",tat:"4.2s"},{name:"Merchant KYB",exec:"32K",success:"89.4%",rejected:"5.8%",manual:"4.8%",tat:"6.1s"},{name:"Re-KYC",exec:"67K",success:"96.1%",rejected:"1.9%",manual:"2.0%",tat:"3.8s"},{name:"Payment Auth",exec:"890K",success:"97.8%",rejected:"1.2%",manual:"1.0%",tat:"0.3s"}];
const frmRules=[{id:1,name:"CC Amount Check",type:"FT",ch:"",st:"Enabled",pri:"High",score:250,alerts:12,fp:3,desc:"Checks if credit card transaction amount exceeds threshold",expr:"orig_transaction_amount > 10000 && orig_payment_method == 'CARD'"},{id:5,name:"Compromised Device",type:"FT (TRANSFER)",ch:"WALLET",st:"Enabled",pri:"Normal",score:195,alerts:8,fp:1,desc:"Device is mocked, Cloned and VPN detected",expr:"orig_device_mockgps && orig_device_appcloned && orig_device_vpnactive"},{id:6,name:"High Value Transfer",type:"FT",ch:"WALLET",st:"Enabled",pri:"High",score:250,alerts:45,fp:12,desc:"Wire transfer exceeds daily threshold",expr:"orig_transaction_amount > 25000 && event_subtype == 'TRANSFER'"},{id:9,name:"Velocity Check",type:"FT",ch:"",st:"Enabled",pri:"Normal",score:150,alerts:23,fp:7,desc:"Multiple transactions in short time window",expr:"transaction_count_1h > 5 || transaction_count_24h > 20"},{id:14,name:"Compromised Login",type:"NFT (LOGIN)",ch:"CARD",st:"Enabled",pri:"Normal",score:200,alerts:5,fp:0,desc:"Login from suspicious device or location",expr:"new_device && geo_anomaly && !mfa_verified"},{id:15,name:"Geo Anomaly",type:"FT (TRANSFER)",ch:"WALLET",st:"Enabled",pri:"High",score:250,alerts:18,fp:4,desc:"Transaction from unexpected geography",expr:"orig_transaction_country != customer_home_country && risk_score > 60"},{id:18,name:"Multi Device Compromise",type:"NFT",ch:"",st:"Active",pri:"High",score:150,alerts:3,fp:0,desc:"Multiple compromised device signals",expr:"orig_device_mockgps && orig_device_appcloned && orig_device_vpnactive"},{id:22,name:"Mule Detection",type:"FT",ch:"WALLET",st:"Enabled",pri:"High",score:220,alerts:7,fp:1,desc:"Suspected mule account behavior",expr:"mule_score > 700 && rapid_fund_movement"},{id:25,name:"Off-Hours Transaction",type:"FT",ch:"CARD",st:"Enabled",pri:"Normal",score:120,alerts:34,fp:15,desc:"Transaction outside normal hours",expr:"transaction_hour < 6 || transaction_hour > 23"},{id:28,name:"New Beneficiary + High Amt",type:"FT (TRANSFER)",ch:"WALLET",st:"Enabled",pri:"High",score:240,alerts:9,fp:2,desc:"High amount to new beneficiary",expr:"is_new_beneficiary && orig_transaction_amount > 5000"},{id:31,name:"SIM Swap Detection",type:"NFT (LOGIN)",ch:"",st:"Enabled",pri:"High",score:250,alerts:2,fp:0,desc:"Recent SIM swap detected",expr:"sim_swap_detected && sim_swap_days < 3"},{id:35,name:"Rapid Account Changes",type:"NFT",ch:"",st:"Enabled",pri:"Normal",score:180,alerts:6,fp:2,desc:"Multiple profile changes in short time",expr:"profile_changes_24h > 3 && includes_email_change"}];
const frmAlerts=[{id:45,rule:"CC Amount Check",amount:"$12.5K",user:"Rajesh Kumar",merchant:"Amazon India Pvt Ltd",score:220,risk:"Low",status:"Resolved",time:"49 min ago",txnId:"983ce0b9-c79f-44d8-b7f6-58c427d839f6",currency:"INR",evType:"FT",evSub:"TRANSFER",channel:"CARD",txnStatus:"PENDING",cardNum:"4111XXXXXXXX1111",cardBal:"$150K",payMethod:"CARD",group:"RISK OFFICERS"},{id:46,rule:"High Value Transfer",amount:"$28.3K",user:"Priya Sharma",merchant:"Wire Transfer",score:450,risk:"High",status:"Active",time:"2 hrs ago",txnId:"a7b2c3d4-e5f6-7890-abcd-ef1234567890",currency:"USD",evType:"FT",evSub:"TRANSFER",channel:"WALLET",txnStatus:"PENDING",cardNum:"",cardBal:"",payMethod:"WALLET",group:"RISK OFFICERS"},{id:47,rule:"Velocity Check",amount:"$890",user:"Alex Chen",merchant:"Multiple Merchants",score:380,risk:"Medium",status:"Pending",time:"3 hrs ago",txnId:"b8c3d4e5-f6a7-8901-bcde-f12345678901",currency:"USD",evType:"FT",evSub:"PURCHASE",channel:"CARD",txnStatus:"COMPLETED",cardNum:"5500XXXXXXXX4444",cardBal:"$8.2K",payMethod:"CARD",group:"FRAUD ANALYSTS"},{id:48,rule:"Geo Anomaly",amount:"$5.2K",user:"Maria Santos",merchant:"International",score:620,risk:"High",status:"Active",time:"5 hrs ago",txnId:"c9d4e5f6-a7b8-9012-cdef-123456789012",currency:"EUR",evType:"FT",evSub:"TRANSFER",channel:"WALLET",txnStatus:"PENDING",cardNum:"",cardBal:"",payMethod:"WALLET",group:"RISK OFFICERS"},{id:49,rule:"Mule Detection",amount:"$15.0K",user:"Viktor Petrov",merchant:"P2P Transfer",score:840,risk:"High",status:"Escalated",time:"6 hrs ago",txnId:"d0e5f6a7-b8c9-0123-defa-234567890123",currency:"USD",evType:"FT",evSub:"P2P",channel:"WALLET",txnStatus:"BLOCKED",cardNum:"",cardBal:"",payMethod:"WALLET",group:"SENIOR ANALYSTS"}];
const Stat=({label,value,delta,color})=>(<div style={{background:"#fff",borderRadius:10,padding:16,border:"1px solid #e5e7eb"}}><p style={{fontSize:11,color:"#9ca3af",fontWeight:600,textTransform:"uppercase",letterSpacing:0.5}}>{label}</p><p style={{fontSize:24,fontWeight:800,color:color||"#111827",marginTop:4,letterSpacing:-0.5}}>{value}</p>{delta&&<div style={{display:"flex",alignItems:"center",gap:3,marginTop:4}}>{delta.startsWith("+")?<ArrowUpRight size={12} color="#059669"/>:<ArrowDownRight size={12} color="#E11D48"/>}<span style={{fontSize:11,fontWeight:600,color:delta.startsWith("+")?"#059669":"#E11D48"}}>{delta}</span></div>}</div>);
const Badge=({text,color})=>(<span style={{fontSize:9,fontWeight:700,padding:"2px 8px",borderRadius:99,background:color+"18",color}}>{text}</span>);
const riskColor=(r)=>r==="Critical"?"#E11D48":r==="High"?"#E11D48":r==="Medium"?"#D97706":"#059669";

function BureauPlatformV2Inner(){
  const searchParams = useSearchParams();
  const pageParam = searchParams.get("page");
  const initialPage = pageParam === "rules" ? "frm" : pageParam === "workflows" ? "workflows" : "dashboard";
  const initialDashTab = pageParam === "aml" ? "aml" : pageParam === "device" ? "device" : "apis";
  
  const[reg]=useState(()=>detectRegion());const rm=regMap[reg]||regMap.US;const tz=Intl.DateTimeFormat().resolvedOptions().timeZone;
  const[time,setTime]=useState("");useEffect(()=>{const u=()=>setTime(new Date().toLocaleTimeString("en-US",{hour12:false,timeZone:tz}));u();const iv=setInterval(u,10000);return()=>clearInterval(iv);},[tz]);
  const[auth,setAuth]=useState(false);const[sideOpen,setSideOpen]=useState(true);const[page,setPage]=useState(initialPage);const[frmSub,setFrmSub]=useState("rules");const[dashTab,setDashTab]=useState(initialDashTab);
  const[selAlert,setSelAlert]=useState(null);const[alertView,setAlertView]=useState(null);const[alertTab,setAlertTab]=useState("details");
  const[modal,setModal]=useState(null);const[timeRange,setTimeRange]=useState("30d");
  const[simRan,setSimRan]=useState(false);const[createRule,setCreateRule]=useState(false);const[editRule,setEditRule]=useState(null);
  const[expanded,setExpanded]=useState({});const[createList,setCreateList]=useState(false);const[viewList,setViewList]=useState(null);
  const[alertActions,setAlertActions]=useState({});const[frmOpen,setFrmOpen]=useState(true);
  const[customRules,setCustomRules]=useState([]);
  const[newRule,setNewRule]=useState({title:"Suspicious International Transfer",desc:"Flags international transfers from new devices with high amounts",expr:'orig_transaction_country != customer_home_country && orig_transaction_amount > 5000 && is_new_device',evType:"FT",evSub:"TRANSFER",chType:"WALLET",score:"200",hiPri:false,enabled:true});
  const[simPayload,setSimPayload]=useState('{\n  "event_type": "FT",\n  "event_subtype": "TRANSFER",\n  "channel_type": "CARD",\n  "transaction_id": "983ce0b9-c79f-44d8-b7f6",\n  "transaction_state": "PENDING",\n  "customer_id": "cust_VeYsy7Kh",\n  "customer_name": "Rajesh Kumar",\n  "orig_transaction_amount": 12500,\n  "orig_transaction_currency": "INR",\n  "orig_payment_method": "CARD",\n  "orig_card_number": "4111XXXXXXXX1111"\n}');
  const[simResult,setSimResult]=useState(null);
  const dateStr=new Date().toISOString().split("T")[0];
  const TimeDD=()=>(<select value={timeRange} onChange={e=>setTimeRange(e.target.value)} style={{padding:"6px 10px",borderRadius:6,border:`1px solid ${T.border}`,fontSize:11,fontWeight:600,fontFamily:T.sans,background:T.white,cursor:"pointer"}}><option value="24h">Last 24 Hours</option><option value="7d">Last 7 Days</option><option value="30d">Last 30 Days</option><option value="90d">Last 90 Days</option><option value="120d">Last 120 Days</option></select>);
  const MiniBar=({data,color=T.primary,h=160,unit=""})=>{const mx=Math.max(...data.map(d=>d.v));const yTicks=[0,Math.round(mx/3),Math.round(mx*2/3),mx];const chartW=data.length*40;const leftPad=50;const chartH=h-40;return(<svg width="100%" height={h} viewBox={`0 0 ${chartW+leftPad} ${h}`} style={{display:"block"}}>{yTicks.map((tick,i)=>{const y=h-25-(tick/mx)*chartH;return(<g key={i}><line x1={leftPad-4} y1={y} x2={chartW+leftPad} y2={y} stroke={T.borderLight} strokeWidth={1} strokeDasharray={i===0?"":"3,3"}/><text x={leftPad-8} y={y+4} textAnchor="end" style={{fontSize:10,fill:T.t400}}>{tick>=1000?(tick/1000).toFixed(1)+"K":tick}{unit}</text></g>);})}{data.map((d,i)=><g key={i}><rect x={leftPad+i*40+8} y={h-25-(d.v/mx)*chartH} width={24} height={(d.v/mx)*chartH} rx={4} fill={color} opacity={0.85}/><text x={leftPad+i*40+20} y={h-8} textAnchor="middle" style={{fontSize:10,fill:T.t400,fontWeight:500}}>{d.l}</text></g>)}</svg>);};
  const MiniLine=({data,color=T.primary,h=160,unit=""})=>{const mx=Math.max(...data.map(d=>d.v));const mn=Math.min(...data.map(d=>d.v));const range=mx-mn||1;const padding=range*0.1;const yMin=mn-padding;const yMax=mx+padding;const yRange=yMax-yMin;const yTicks=[yMin,yMin+yRange/2,yMax];const leftPad=50;const chartW=280;const chartH=h-50;const getY=(v)=>h-30-((v-yMin)/yRange)*chartH;const pts=data.map((d,i)=>`${leftPad+i*((chartW-leftPad)/(data.length-1))},${getY(d.v)}`).join(" ");return(<svg width="100%" height={h} viewBox={`0 0 ${chartW} ${h}`} style={{display:"block"}}>{yTicks.map((tick,i)=>{const y=getY(tick);return(<g key={i}><line x1={leftPad-4} y1={y} x2={chartW} y2={y} stroke={T.borderLight} strokeWidth={1} strokeDasharray="3,3"/><text x={leftPad-8} y={y+4} textAnchor="end" style={{fontSize:10,fill:T.t400}}>{tick>=1000?(tick/1000).toFixed(1)+"K":Number(tick).toFixed(1)}{unit}</text></g>);})}<polyline points={pts} fill="none" stroke={color} strokeWidth={2.5} strokeLinejoin="round" strokeLinecap="round"/><polygon points={`${pts} ${chartW},${h-30} ${leftPad},${h-30}`} fill={color} opacity={0.1}/>{data.map((d,i)=><circle key={i} cx={leftPad+i*((chartW-leftPad)/(data.length-1))} cy={getY(d.v)} r={4} fill={color}/>)}{data.map((d,i)=><text key={i} x={leftPad+i*((chartW-leftPad)/(data.length-1))} y={h-10} textAnchor="middle" style={{fontSize:10,fill:T.t400,fontWeight:500}}>{d.l}</text>)}</svg>);};
  const csvDownload=()=>{try{const b=new Blob(["Rule ID,Rule Name,Channel Type,Event Type,Status,Priority,Score,Alerts Generated,Confirmed Fraud,False Positives,Pending Count\n"],{type:"text/csv"});const u=URL.createObjectURL(b);const a=document.createElement("a");a.href=u;a.download="bureau_frm_report.csv";document.body.appendChild(a);a.click();document.body.removeChild(a);setTimeout(()=>URL.revokeObjectURL(u),1000);}catch(e){console.error(e);}};
  const approvePayload='{\n  "event_type": "FT",\n  "event_subtype": "PURCHASE",\n  "channel_type": "CARD",\n  "transaction_id": "clean-txn-001",\n  "transaction_state": "PENDING",\n  "customer_id": "cust_trusted",\n  "customer_name": "Sarah Mitchell",\n  "orig_transaction_amount": 150,\n  "orig_transaction_currency": "USD",\n  "orig_payment_method": "CARD",\n  "orig_card_number": "4242XXXXXXXX4242",\n  "customer_status": "ACTIVE",\n  "is_new_device": false,\n  "geo_anomaly": false\n}';
  const rejectPayload='{\n  "event_type": "FT",\n  "event_subtype": "TRANSFER",\n  "channel_type": "WALLET",\n  "transaction_id": "fraud-txn-099",\n  "transaction_state": "PENDING",\n  "customer_id": "cust_suspicious",\n  "customer_name": "Unknown Actor",\n  "orig_transaction_amount": 49999,\n  "orig_transaction_currency": "USD",\n  "orig_payment_method": "WALLET",\n  "orig_transaction_country": "NG",\n  "is_new_device": true,\n  "is_new_beneficiary": true,\n  "geo_anomaly": true,\n  "mule_score": 890,\n  "device_vpn": true\n}';
  const togExp=(k)=>setExpanded(p=>({...p,[k]:!p[k]}));

  if(!auth)return(
    <div style={{fontFamily:T.sans,minHeight:"100vh",background:`linear-gradient(135deg,${T.navy900} 0%,${T.primary} 50%,#1A2B5C 100%)`,display:"flex",alignItems:"center",justifyContent:"center",WebkitFontSmoothing:"antialiased"}}>
      <div style={{width:400,background:T.white,borderRadius:16,padding:40,boxShadow:"0 24px 80px rgba(0,0,0,0.3)"}}>
        <div style={{textAlign:"center",marginBottom:32}}><div style={{display:"flex",alignItems:"center",justifyContent:"center",marginBottom:6}}><img src={BUREAU_LOGO} alt="Bureau" style={{height:32}}/></div><p style={{fontSize:13,color:T.t400}}>Sign in to your platform</p></div>
        <div style={{marginBottom:16}}><label style={{fontSize:12,fontWeight:600,color:T.t700,display:"block",marginBottom:4}}>Email</label><div style={{display:"flex",alignItems:"center",gap:8,padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,background:T.bg}}><Mail size={16} color={T.t400}/><span style={{fontSize:13,color:T.t900}}>yash.gajra@bureau.id</span></div></div>
        <div style={{marginBottom:24}}><label style={{fontSize:12,fontWeight:600,color:T.t700,display:"block",marginBottom:4}}>Password</label><div style={{display:"flex",alignItems:"center",gap:8,padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,background:T.bg}}><Lock size={16} color={T.t400}/><span style={{fontSize:13,color:T.t900,letterSpacing:2}}>••••••••</span></div></div>
        <button onClick={()=>setAuth(true)} style={{width:"100%",padding:13,borderRadius:10,background:T.primary,color:"#fff",fontSize:14,fontWeight:700,border:"none",cursor:"pointer",fontFamily:T.sans}}>Sign In</button>
        <p style={{fontSize:12,color:T.primary,textAlign:"center",marginTop:14,cursor:"pointer",fontWeight:600}}>Forgot password?</p>
      </div>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700;9..40,800&family=JetBrains+Mono:wght@400;500;600&display=swap');*{box-sizing:border-box;margin:0;}`}</style>
    </div>
  );

  const navItems=[{id:"dashboard",icon:LayoutDashboard,label:"Dashboard"},{id:"workflows",icon:GitBranch,label:"Workflows"},{id:"profiles",icon:Users,label:"Profiles"},{id:"frm",icon:AlertTriangle,label:"Transaction Monitoring",sub:[{id:"rules",label:"Rules"},{id:"simulator",label:"Simulator"},{id:"alerts",label:"Alerts"},{id:"lists",label:"Lists"},{id:"reports",label:"Reports"}]}];
  const Modal=({title,children,onClose})=>(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.4)",display:"flex",alignItems:"center",justifyContent:"center",zIndex:100}} onClick={onClose}><div style={{background:T.white,borderRadius:14,padding:24,width:500,maxHeight:"80vh",overflowY:"auto",boxShadow:"0 20px 60px rgba(0,0,0,0.2)"}} onClick={e=>e.stopPropagation()}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><h3 style={{fontSize:16,fontWeight:700}}>{title}</h3><X size={18} color={T.t400} style={{cursor:"pointer"}} onClick={onClose}/></div>{children}</div></div>);
  const ExpandSection=({title,children})=>{const open=expanded[title];return(<div style={{background:T.white,borderRadius:10,border:`1px solid ${T.border}`,marginBottom:6,overflow:"hidden"}}><div onClick={()=>togExp(title)} style={{padding:"12px 14px",display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer"}}><span style={{fontSize:13,fontWeight:600}}>{title}</span>{open?<ChevronUp size={16} color={T.t400}/>:<ChevronDown size={16} color={T.t400}/>}</div>{open&&<div style={{padding:"0 14px 14px",borderTop:`1px solid ${T.borderLight}`}}>{children}</div>}</div>);};

  const apiBarData=[{l:"Mon",v:2450},{l:"Tue",v:3120},{l:"Wed",v:2890},{l:"Thu",v:3540},{l:"Fri",v:3210},{l:"Sat",v:1680},{l:"Sun",v:1420}];
  const execBarData=[{l:"Mon",v:185},{l:"Tue",v:210},{l:"Wed",v:165},{l:"Thu",v:245},{l:"Fri",v:290},{l:"Sat",v:125},{l:"Sun",v:95}];
  const detectBarData=[{l:"Mon",v:145},{l:"Tue",v:312},{l:"Wed",v:285},{l:"Thu",v:198},{l:"Fri",v:256},{l:"Sat",v:89},{l:"Sun",v:124}];
  const screenBarData=[{l:"Mon",v:520},{l:"Tue",v:485},{l:"Wed",v:590},{l:"Thu",v:680},{l:"Fri",v:625},{l:"Sat",v:380},{l:"Sun",v:295}];
  const latencyLineData=[{l:"6am",v:125},{l:"9am",v:142},{l:"12pm",v:168},{l:"3pm",v:155},{l:"6pm",v:148},{l:"9pm",v:132},{l:"12am",v:118}];
  const successLineData=[{l:"Mon",v:99.2},{l:"Tue",v:99.5},{l:"Wed",v:99.1},{l:"Thu",v:99.8},{l:"Fri",v:99.6},{l:"Sat",v:99.9},{l:"Sun",v:99.7}];
  const threatLineData=[{l:"Mon",v:12},{l:"Tue",v:28},{l:"Wed",v:45},{l:"Thu",v:38},{l:"Fri",v:52},{l:"Sat",v:31},{l:"Sun",v:18}];
  const hitRateLineData=[{l:"Mon",v:2.4},{l:"Tue",v:2.1},{l:"Wed",v:3.2},{l:"Thu",v:2.8},{l:"Fri",v:3.5},{l:"Sat",v:2.9},{l:"Sun",v:2.2}];

  const renderPage=()=>{
    /* DASHBOARD */
    if(page==="dashboard")return(<div>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",marginBottom:16}}>
        <div style={{display:"flex",gap:8,borderBottom:`1px solid ${T.border}`,flex:1,marginRight:16}}>
          {["apis","workflows","device","aml"].map(t=>(<button key={t} onClick={()=>setDashTab(t)} style={{padding:"10px 18px",fontSize:13,fontWeight:dashTab===t?700:500,color:dashTab===t?T.primary:T.t400,background:"none",border:"none",borderBottom:dashTab===t?`2px solid ${T.primary}`:"2px solid transparent",cursor:"pointer",fontFamily:T.sans,marginBottom:-1}}>{t==="apis"?"APIs":t==="device"?"Device Intelligence":t==="workflows"?"Workflows":"AML"}</button>))}
        </div>
        <div style={{marginBottom:8}}><TimeDD/></div>
      </div>
      {dashTab==="apis"&&<div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:16}}><Stat label="Total API Calls" value="5.99M" delta="+18%"/><Stat label="Avg Latency" value="198ms" delta="-12%"/><Stat label="Success Rate" value="99.1%" delta="+0.3%"/><Stat label="Active Endpoints" value="6"/></div>
        <div style={{background:T.white,borderRadius:10,border:`1px solid ${T.border}`,overflow:"hidden",marginBottom:16}}><div style={{padding:"14px 16px",borderBottom:`1px solid ${T.border}`,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:13,fontWeight:700}}>API Performance</span><span style={{fontSize:10,color:T.t400}}>{timeRange}</span></div>
          <table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:T.bg}}>{["Service","Volume","Success","P50","P99","Trend","Status"].map(h=><th key={h} style={{padding:"10px 14px",textAlign:"left",fontWeight:600,color:T.t400,fontSize:10,textTransform:"uppercase",letterSpacing:0.5}}>{h}</th>)}</tr></thead>
          <tbody>{dashAPIs.map((a,i)=><tr key={i} style={{borderBottom:`1px solid ${T.borderLight}`}}><td style={{padding:"12px 14px",fontWeight:600,color:T.t900}}>{a.name}</td><td style={{padding:"12px 14px",color:T.t700}}>{a.calls}</td><td style={{padding:"12px 14px",color:T.emerald,fontWeight:600}}>{a.success}</td><td style={{padding:"12px 14px",fontFamily:T.mono,fontSize:11,color:T.t500}}>{a.p50}</td><td style={{padding:"12px 14px",fontFamily:T.mono,fontSize:11,color:T.t500}}>{a.p99}</td><td style={{padding:"12px 14px"}}><span style={{color:T.emerald,fontWeight:600,fontSize:11}}>{a.trend}</span></td><td style={{padding:"12px 14px"}}><Badge text="Healthy" color={T.emerald}/></td></tr>)}</tbody></table></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><p style={{fontSize:14,fontWeight:700}}>API Call Volume</p><span style={{fontSize:11,color:T.t400,background:T.bg,padding:"4px 10px",borderRadius:6}}>calls/day</span></div><MiniBar data={apiBarData} color={T.primary} h={180}/></div>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><p style={{fontSize:14,fontWeight:700}}>Latency Trend (P50)</p><span style={{fontSize:11,color:T.t400,background:T.bg,padding:"4px 10px",borderRadius:6}}>milliseconds</span></div><MiniLine data={latencyLineData} color={T.primary} h={180} unit="ms"/></div>
        </div>
      </div>}
      {dashTab==="workflows"&&<div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:16}}><Stat label="Total Executions" value="1.13M" delta="+22%"/><Stat label="Success Rate" value="94.8%" delta="+1.2%"/><Stat label="Avg TAT" value="3.8s" delta="-15%"/><Stat label="Active Workflows" value="4"/></div>
        <div style={{background:T.white,borderRadius:10,border:`1px solid ${T.border}`,overflow:"hidden",marginBottom:16}}><div style={{padding:"14px 16px",borderBottom:`1px solid ${T.border}`}}><span style={{fontSize:13,fontWeight:700}}>Workflow Performance</span></div>
          <table style={{width:"100%",borderCollapse:"collapse",fontSize:12}}><thead><tr style={{background:T.bg}}>{["Workflow","Executions","Success","Rejected","Manual","TAT"].map(h=><th key={h} style={{padding:"10px 14px",textAlign:"left",fontWeight:600,color:T.t400,fontSize:10,textTransform:"uppercase",letterSpacing:0.5}}>{h}</th>)}</tr></thead>
          <tbody>{dashWF.map((w,i)=><tr key={i} style={{borderBottom:`1px solid ${T.borderLight}`}}><td style={{padding:"12px 14px",fontWeight:600,color:T.t900}}>{w.name}</td><td style={{padding:"12px 14px",color:T.t700}}>{w.exec}</td><td style={{padding:"12px 14px",color:T.emerald,fontWeight:600}}>{w.success}</td><td style={{padding:"12px 14px",color:T.rose,fontWeight:600}}>{w.rejected}</td><td style={{padding:"12px 14px",color:T.amber,fontWeight:600}}>{w.manual}</td><td style={{padding:"12px 14px",fontFamily:T.mono,fontSize:11}}>{w.tat}</td></tr>)}</tbody></table></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><p style={{fontSize:14,fontWeight:700}}>Execution Volume</p><span style={{fontSize:11,color:T.t400,background:T.bg,padding:"4px 10px",borderRadius:6}}>executions/day</span></div><MiniBar data={execBarData} color={T.emerald} h={180}/></div>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><p style={{fontSize:14,fontWeight:700}}>Success Rate Trend</p><span style={{fontSize:11,color:T.t400,background:T.bg,padding:"4px 10px",borderRadius:6}}>percentage</span></div><MiniLine data={successLineData} color={T.emerald} h={180} unit="%"/></div>
        </div>
      </div>}
      {dashTab==="device"&&<div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:16}}>{[{s:"Unique Devices",v:"4.2M",d:"+18%",c:T.violet},{s:"Bot Detections",v:"12,847",d:"+45%",c:T.rose},{s:"Emulators Blocked",v:"3,291",d:"+22%",c:T.amber},{s:"Jailbreak Detected",v:"8,104",d:"-5%",c:T.orange}].map((d,i)=><Stat key={i} label={d.s} value={d.v} delta={d.d} color={d.c}/>)}</div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><p style={{fontSize:14,fontWeight:700}}>Detection Volume</p><span style={{fontSize:11,color:T.t400,background:T.bg,padding:"4px 10px",borderRadius:6}}>threats/day</span></div><MiniBar data={detectBarData} color={T.violet} h={180}/></div>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><p style={{fontSize:14,fontWeight:700}}>Threat Trend</p><span style={{fontSize:11,color:T.t400,background:T.bg,padding:"4px 10px",borderRadius:6}}>alerts/day</span></div><MiniLine data={threatLineData} color={T.rose} h={180}/></div>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><p style={{fontSize:14,fontWeight:700,marginBottom:16}}>Top Threat Signals</p>{[{s:"Emulator Detected",v:"3,847"},{s:"Jailbreak/Root",v:"2,104"},{s:"App Tampering",v:"1,892"},{s:"VPN/Proxy Active",v:"1,654"},{s:"Mock GPS Location",v:"987"},{s:"App Clone Detected",v:"543"}].map((d,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:i<5?`1px solid ${T.borderLight}`:"none"}}><span style={{fontSize:13}}>{d.s}</span><span style={{fontSize:13,fontWeight:700,color:T.violet,fontFamily:T.mono}}>{d.v}</span></div>)}</div>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><p style={{fontSize:14,fontWeight:700,marginBottom:16}}>Device Distribution</p>{[{l:"iOS",v:62,c:T.primary},{l:"Android",v:35,c:T.emerald},{l:"Web",v:3,c:T.amber}].map((d,i)=><div key={i} style={{marginBottom:14}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:13}}>{d.l}</span><span style={{fontSize:13,fontWeight:700,color:d.c}}>{d.v}%</span></div><div style={{height:8,background:T.borderLight,borderRadius:4}}><div style={{height:"100%",background:d.c,borderRadius:4,width:`${d.v}%`,transition:"width 0.3s"}}/></div></div>)}</div>
        </div>
      </div>}
      {dashTab==="aml"&&<div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:16}}>{[{m:"Screenings",v:"430K",d:"+5%"},{m:"Watchlist Hits",v:"1,247",d:"+12%"},{m:"PEP Matches",v:"342",d:"-3%"},{m:"Cases Created",v:"89",d:"+8%"}].map((a,i)=><Stat key={i} label={a.m} value={a.v} delta={a.d}/>)}</div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><p style={{fontSize:14,fontWeight:700}}>Screening Volume</p><span style={{fontSize:11,color:T.t400,background:T.bg,padding:"4px 10px",borderRadius:6}}>screenings/day</span></div><MiniBar data={screenBarData} color={T.teal} h={180}/></div>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><p style={{fontSize:14,fontWeight:700}}>Hit Rate Trend</p><span style={{fontSize:11,color:T.t400,background:T.bg,padding:"4px 10px",borderRadius:6}}>hit rate %</span></div><MiniLine data={hitRateLineData} color={T.rose} h={180} unit="%"/></div>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><p style={{fontSize:14,fontWeight:700,marginBottom:16}}>Watchlist Coverage</p>{[{l:"OFAC SDN",u:"1.2M"},{l:"UN Sanctions",u:"24K"},{l:"EU Sanctions",u:"18K"},{l:"UK HMT",u:"12K"},{l:"PEP Database",u:"4.8M"},{l:"Adverse Media",u:"890K"}].map((d,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:i<5?`1px solid ${T.borderLight}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:"50%",background:T.emerald}}/><span style={{fontSize:13}}>{d.l}</span></div><span style={{fontSize:12,color:T.t400,fontFamily:T.mono}}>{d.u} records</span></div>)}</div>
          <div style={{background:T.white,borderRadius:12,padding:20,border:`1px solid ${T.border}`}}><p style={{fontSize:14,fontWeight:700,marginBottom:16}}>Resolution Rate</p>{[{l:"Auto-Cleared",v:87,c:T.emerald},{l:"Manual Review",v:9,c:T.amber},{l:"Escalated",v:3,c:T.rose},{l:"Pending",v:1,c:T.t400}].map((r,i)=><div key={i} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{fontSize:13}}>{r.l}</span><span style={{fontSize:13,fontWeight:700,color:r.c}}>{r.v}%</span></div><div style={{height:8,background:T.borderLight,borderRadius:4}}><div style={{height:"100%",background:r.c,borderRadius:4,width:`${r.v}%`,transition:"width 0.3s"}}/></div></div>)}</div>
        </div>
      </div>}
    </div>);

    /* WORKFLOWS - blank */
    if(page==="workflows")return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",height:400}}><GitBranch size={48} color={T.t300}/><p style={{fontSize:16,fontWeight:700,color:T.t900,marginTop:12}}>Workflow Builder</p><p style={{fontSize:12,color:T.t400,marginTop:4}}>Coming soon — design and manage verification workflows</p></div>);

    /* PROFILES - blank */
    if(page==="profiles")return(<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",height:400}}><Users size={48} color={T.t300}/><p style={{fontSize:16,fontWeight:700,color:T.t900,marginTop:12}}>Profiles</p><p style={{fontSize:12,color:T.t400,marginTop:4}}>Coming soon — customer risk profiles and activity</p></div>);

    /* FRM RULES */
    if(page==="frm"&&frmSub==="rules"){
      if(createRule)return(<div>
        <button onClick={()=>setCreateRule(false)} style={{display:"flex",alignItems:"center",gap:4,background:"none",border:"none",color:T.t400,fontSize:12,cursor:"pointer",marginBottom:12,fontFamily:T.sans}}><ArrowLeft size={14}/>Back to Rules</button>
        <h2 style={{fontSize:20,fontWeight:700,marginBottom:16}}>Create new rule</h2>
        <div style={{maxWidth:700}}>
          <div style={{marginBottom:20}}><label style={{fontSize:14,fontWeight:700,display:"block",marginBottom:6}}>Title</label><input value={newRule.title} onChange={e=>setNewRule(p=>({...p,title:e.target.value}))} placeholder="Enter a title for this rule" style={{width:"100%",padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:13,fontFamily:T.sans}}/><p style={{fontSize:11,color:T.primary,marginTop:4}}>A short, descriptive title for the rule</p></div>
          <div style={{marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between"}}><label style={{fontSize:14,fontWeight:700}}>Description</label><span style={{fontSize:11,color:T.t400,cursor:"pointer"}}>✨ Generate with AI</span></div><input value={newRule.desc} onChange={e=>setNewRule(p=>({...p,desc:e.target.value}))} placeholder="Enter a descriptive name" style={{width:"100%",padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:13,fontFamily:T.sans,marginTop:6}}/><p style={{fontSize:11,color:T.primary,marginTop:4}}>A clear description of what this rule checks for</p></div>
          <div style={{marginBottom:20}}><div style={{display:"flex",justifyContent:"space-between"}}><label style={{fontSize:14,fontWeight:700}}>Expression</label><span style={{fontSize:11,color:T.primary,cursor:"pointer"}}>☰ View Fields</span></div><textarea value={newRule.expr} onChange={e=>setNewRule(p=>({...p,expr:e.target.value}))} placeholder="Enter the rule expression" style={{width:"100%",padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:12,fontFamily:T.mono,height:100,resize:"vertical",marginTop:6}}/><p style={{fontSize:11,color:T.primary,marginTop:4}}>The CEL expression that defines the rule logic</p></div>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:16,marginBottom:20}}>
            <div><label style={{fontSize:14,fontWeight:700,display:"block",marginBottom:6}}>Event Type</label><select value={newRule.evType} onChange={e=>setNewRule(p=>({...p,evType:e.target.value}))} style={{width:"100%",padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:13,fontFamily:T.sans}}><option value="">Select event type</option><option value="FT">FT (Financial)</option><option value="NFT">NFT (Non-Financial)</option></select></div>
            <div><label style={{fontSize:14,fontWeight:700,display:"block",marginBottom:6}}>Event Subtype</label><select value={newRule.evSub} onChange={e=>setNewRule(p=>({...p,evSub:e.target.value}))} style={{width:"100%",padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:13,fontFamily:T.sans}}><option value="">Select subtype</option><option value="TRANSFER">TRANSFER</option><option value="PURCHASE">PURCHASE</option><option value="DEPOSIT">DEPOSIT</option><option value="LOGIN">LOGIN</option></select></div>
            <div><label style={{fontSize:14,fontWeight:700,display:"block",marginBottom:6}}>Channel Type</label><select value={newRule.chType} onChange={e=>setNewRule(p=>({...p,chType:e.target.value}))} style={{width:"100%",padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:13,fontFamily:T.sans}}><option value="">Select channel</option><option value="CARD">CARD</option><option value="WALLET">WALLET</option><option value="BANK">BANK</option></select></div>
          </div>
          <div style={{marginBottom:20}}><label style={{fontSize:14,fontWeight:700,display:"block",marginBottom:6}}>Rule Score</label><input type="number" value={newRule.score} onChange={e=>setNewRule(p=>({...p,score:e.target.value}))} placeholder="1-250" style={{width:"100%",padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:13,fontFamily:T.sans}}/><p style={{fontSize:11,color:T.primary,marginTop:4}}>A numeric value ranging from 1 to 250</p></div>
          <div style={{display:"flex",flexDirection:"column",gap:14,marginBottom:24}}>
            <div onClick={()=>setNewRule(p=>({...p,hiPri:!p.hiPri}))} style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}}><div style={{width:42,height:24,borderRadius:12,background:newRule.hiPri?T.primary:T.t300,padding:2,transition:"all 0.2s"}}><div style={{width:20,height:20,borderRadius:"50%",background:"#fff",boxShadow:"0 1px 3px rgba(0,0,0,0.2)",transform:newRule.hiPri?"translateX(18px)":"translateX(0)",transition:"all 0.2s"}}/></div><div><p style={{fontSize:13,fontWeight:600}}>High Priority Rule</p><p style={{fontSize:11,color:T.t400}}>High priority rules execute first and can stop execution of regular rules</p></div></div>
            <div onClick={()=>setNewRule(p=>({...p,enabled:!p.enabled}))} style={{display:"flex",alignItems:"center",gap:10,cursor:"pointer"}}><div style={{width:42,height:24,borderRadius:12,background:newRule.enabled?T.primary:T.t300,padding:2,transition:"all 0.2s"}}><div style={{width:20,height:20,borderRadius:"50%",background:"#fff",boxShadow:"0 1px 3px rgba(0,0,0,0.2)",transform:newRule.enabled?"translateX(18px)":"translateX(0)",transition:"all 0.2s"}}/></div><div><p style={{fontSize:13,fontWeight:600}}>Enable rule immediately</p></div></div>
          </div>
          <div style={{display:"flex",justifyContent:"flex-end"}}><button onClick={()=>{const nr={id:100+customRules.length,name:newRule.title,type:newRule.evType+(newRule.evSub?` (${newRule.evSub})`:""),ch:newRule.chType,st:newRule.enabled?"Enabled":"Disabled",pri:newRule.hiPri?"High":"Normal",score:parseInt(newRule.score)||150,alerts:0,fp:0,desc:newRule.desc,expr:newRule.expr};setCustomRules(p=>[nr,...p]);setCreateRule(false);setNewRule({title:"",desc:"",expr:"",evType:"",evSub:"",chType:"",score:"150",hiPri:false,enabled:true});}} style={{padding:"10px 24px",borderRadius:8,background:T.primary,color:"#fff",border:"none",fontSize:13,fontWeight:700,cursor:"pointer",fontFamily:T.sans}}>Create Rule</button></div>
        </div>
      </div>);
      if(editRule)return(<div>
        <button onClick={()=>setEditRule(null)} style={{display:"flex",alignItems:"center",gap:4,background:"none",border:"none",color:T.t400,fontSize:12,cursor:"pointer",marginBottom:12,fontFamily:T.sans}}><ArrowLeft size={14}/>Back to Rules</button>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><h2 style={{fontSize:18,fontWeight:700}}>Rule Details</h2><div style={{display:"flex",gap:6}}><button onClick={()=>setEditRule(null)} style={{display:"flex",alignItems:"center",gap:4,padding:"7px 14px",borderRadius:6,background:T.white,color:T.t700,border:`1px solid ${T.border}`,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}><X size={13}/>Cancel</button><button onClick={()=>setEditRule(null)} style={{display:"flex",alignItems:"center",gap:4,padding:"7px 14px",borderRadius:6,background:T.primary,color:"#fff",border:"none",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}><Save size={13}/>Save Changes</button></div></div>
        <div style={{display:"grid",gridTemplateColumns:"280px 1fr",gap:16}}>
          <div style={{background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`}}>
            <h3 style={{fontSize:16,fontWeight:700,marginBottom:4}}>Rule Information</h3>
            <Badge text={editRule.st} color={T.emerald}/>
            {[{l:"Rule ID",v:editRule.id},{l:"Created On",v:"Feb 20, 2026, 02:30 AM"},{l:"Last Updated",v:"Feb 20, 2026, 02:35 AM"},{l:"Created By",v:"Yash Gajra"}].map((f,i)=><div key={i} style={{padding:"8px 0",borderBottom:i<3?`1px solid ${T.borderLight}`:"none"}}><p style={{fontSize:10,color:T.t400}}>{f.l}</p><p style={{fontSize:12,fontWeight:600}}>{f.v}</p></div>)}
          </div>
          <div style={{background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`}}>
            <p style={{fontSize:16,fontWeight:700,marginBottom:16}}>{editRule.name}</p>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
              <div><label style={{fontSize:11,color:T.primary,fontWeight:600}}>Rule Status</label><div style={{display:"flex",alignItems:"center",gap:8,marginTop:4}}><span style={{fontSize:12,fontWeight:600}}>Enabled</span><div style={{width:40,height:22,borderRadius:11,background:T.primary,cursor:"pointer",position:"relative"}}><div style={{width:18,height:18,borderRadius:"50%",background:"#fff",position:"absolute",top:2,right:2,boxShadow:"0 1px 3px rgba(0,0,0,0.2)"}}/></div></div></div>
              <div><label style={{fontSize:11,color:T.primary,fontWeight:600}}>Priority Level</label><div style={{display:"flex",alignItems:"center",gap:8,marginTop:4}}><span style={{fontSize:12,fontWeight:600}}>High Priority Rule</span><div style={{width:40,height:22,borderRadius:11,background:editRule.pri==="High"?T.primary:T.t300,cursor:"pointer",position:"relative"}}><div style={{width:18,height:18,borderRadius:"50%",background:"#fff",position:"absolute",top:2,right:editRule.pri==="High"?2:"auto",left:editRule.pri==="High"?"auto":2,boxShadow:"0 1px 3px rgba(0,0,0,0.2)"}}/></div></div></div>
            </div>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
              <div><label style={{fontSize:11,color:T.primary,fontWeight:600}}>Channel Type</label><select style={{width:"100%",padding:"8px 12px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:12,fontFamily:T.sans,marginTop:4}}><option>{editRule.ch||"Select a channel type"}</option></select></div>
              <div><label style={{fontSize:11,color:T.primary,fontWeight:600}}>Rule Score</label><input defaultValue={editRule.score} style={{width:"100%",padding:"8px 12px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:12,fontFamily:T.sans,marginTop:4}}/><p style={{fontSize:10,color:T.t400,marginTop:2}}>A numeric value ranging from 1 to 250</p></div>
            </div>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
              <div><label style={{fontSize:11,color:T.primary,fontWeight:600}}>Event Type</label><select style={{width:"100%",padding:"8px 12px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:12,fontFamily:T.sans,marginTop:4}}><option>{editRule.type}</option></select></div>
              <div><label style={{fontSize:11,color:T.primary,fontWeight:600}}>Event Subtype</label><select style={{width:"100%",padding:"8px 12px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:12,fontFamily:T.sans,marginTop:4}}><option>Select an event subtype</option></select></div>
            </div>
            <div style={{marginBottom:16}}><div style={{display:"flex",justifyContent:"space-between"}}><label style={{fontSize:11,color:T.primary,fontWeight:600}}>Description</label><span style={{fontSize:10,color:T.t400}}>✨ Generate with AI</span></div><input defaultValue={editRule.desc} style={{width:"100%",padding:"8px 12px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:12,fontFamily:T.sans,marginTop:4}}/></div>
            <div><div style={{display:"flex",justifyContent:"space-between"}}><label style={{fontSize:11,color:T.primary,fontWeight:600}}>Rule Expression</label><span style={{fontSize:10,color:T.primary}}>View Fields</span></div><textarea defaultValue={editRule.expr} style={{width:"100%",padding:"10px 12px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:11,fontFamily:T.mono,height:80,marginTop:4,resize:"vertical"}}/></div>
          </div>
        </div>
      </div>);
      return(<div>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><div><h2 style={{fontSize:18,fontWeight:700}}>Rules</h2><p style={{fontSize:12,color:T.t400}}>View and manage fraud detection rules</p></div><div style={{display:"flex",gap:8,alignItems:"center"}}><Badge text={`Active (${frmRules.filter(r=>r.st==="Enabled").length})`} color={T.emerald}/><Badge text={`High Priority (${frmRules.filter(r=>r.pri==="High").length})`} color={T.rose}/><button onClick={()=>setCreateRule(true)} style={{display:"flex",alignItems:"center",gap:6,padding:"8px 16px",borderRadius:8,background:T.primary,color:"#fff",border:"none",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}><Plus size={14}/>Create Rule</button></div></div>
        <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10}}>
          {[...customRules,...frmRules].map(r=>(<div key={r.id} onClick={()=>setEditRule(r)} style={{background:T.white,borderRadius:10,padding:14,border:`1px solid ${T.border}`,borderLeft:`3px solid ${r.pri==="High"?T.rose:T.emerald}`,cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}>{r.pri==="High"&&<Badge text="High Priority" color={T.rose}/>}<Badge text={r.st} color={r.st==="Enabled"||r.st==="Active"?T.emerald:T.t400}/></div><p style={{fontSize:13,fontWeight:700,marginBottom:4}}>{r.name}</p><div style={{display:"flex",gap:12,fontSize:10,color:T.t400}}><span>Type: {r.type}</span>{r.ch&&<span>Ch: {r.ch}</span>}</div><div style={{display:"flex",gap:12,marginTop:8,padding:"6px 0 0",borderTop:`1px solid ${T.borderLight}`}}><div><p style={{fontSize:9,color:T.t400}}>Score</p><p style={{fontSize:13,fontWeight:700}}>{r.score}</p></div><div><p style={{fontSize:9,color:T.t400}}>Alerts</p><p style={{fontSize:13,fontWeight:700,color:T.amber}}>{r.alerts}</p></div><div><p style={{fontSize:9,color:T.t400}}>False Pos</p><p style={{fontSize:13,fontWeight:700,color:T.rose}}>{r.fp}</p></div></div></div>))}
        </div>
      </div>);
    }

    /* FRM SIMULATOR */
    if(page==="frm"&&frmSub==="simulator")return(<div>
      <h2 style={{fontSize:18,fontWeight:700,marginBottom:4}}>Simulator</h2><p style={{fontSize:12,color:T.t400,marginBottom:16}}>Test and debug rule evaluations</p>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
        <div style={{background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12}}><span style={{fontSize:13,fontWeight:700}}>Transaction Payload</span><div style={{display:"flex",gap:4}}><button onClick={()=>{setSimPayload(approvePayload);setSimRan(false);setSimResult(null);}} style={{padding:"4px 10px",borderRadius:6,background:T.emeraldBg,border:`1px solid ${T.emerald}30`,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:T.sans,color:T.emerald}}>✓ Approve Sample</button><button onClick={()=>{setSimPayload(rejectPayload);setSimRan(false);setSimResult(null);}} style={{padding:"4px 10px",borderRadius:6,background:T.roseBg,border:`1px solid ${T.rose}30`,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:T.sans,color:T.rose}}>✗ Reject Sample</button></div></div>
          <textarea value={simPayload} onChange={e=>setSimPayload(e.target.value)} spellCheck={false} style={{width:"100%",background:T.t900,borderRadius:8,padding:14,fontSize:10,color:"#a5f3fc",lineHeight:1.7,fontFamily:T.mono,height:300,resize:"vertical",border:"none",display:"block"}}/>
          <button onClick={()=>{const isR=simPayload.includes("49999")||simPayload.includes("fraud")||simPayload.includes("mule_score");setSimRan(true);setSimResult(isR?"reject":"approve");}} style={{width:"100%",padding:12,borderRadius:8,background:T.primary,color:"#fff",fontSize:13,fontWeight:700,border:"none",cursor:"pointer",marginTop:12,fontFamily:T.sans}}>Evaluate Rules</button></div>
        <div style={{background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`}}>
          <span style={{fontSize:13,fontWeight:700}}>Evaluation Results</span>
          {!simRan?(<div style={{display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center",height:340,color:T.t400}}><Activity size={40} color={T.t300}/><p style={{fontSize:12,marginTop:10,color:T.primary}}>Evaluation results will appear here after you evaluate a payload.</p></div>):(
            simResult==="reject"?(<><div style={{marginTop:12,padding:16,background:T.roseBg,borderRadius:8,border:`1px solid ${T.rose}20`}}><p style={{fontSize:11,fontWeight:700,color:T.t400,textTransform:"uppercase",marginBottom:4}}>Risk Assessment</p><div style={{display:"flex",gap:20}}><div><p style={{fontSize:10,color:T.t400}}>Category</p><p style={{fontSize:14,fontWeight:700,color:T.rose}}>High Risk</p></div><div><p style={{fontSize:10,color:T.t400}}>Score</p><p style={{fontSize:14,fontWeight:700}}>840/1000</p></div><div><p style={{fontSize:10,color:T.t400}}>Action</p><p style={{fontSize:14,fontWeight:700,color:T.rose}}>BLOCK</p></div></div></div><div style={{marginTop:12}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:11,fontWeight:700,color:T.t400,textTransform:"uppercase"}}>Flagged Rules</span><Badge text="Transaction Blocked" color={T.rose}/></div><p style={{fontSize:20,fontWeight:800,marginTop:4}}>5/7</p></div><button onClick={()=>{setPage("frm");setFrmSub("alerts");setSimRan(false);setSimResult(null);}} style={{width:"100%",padding:10,borderRadius:8,background:T.bg,color:T.t700,fontSize:12,fontWeight:600,border:`1px solid ${T.border}`,cursor:"pointer",marginTop:12,fontFamily:T.sans}}>Go to Alert</button></>)
            :(<><div style={{marginTop:12,padding:16,background:T.emeraldBg,borderRadius:8,border:`1px solid ${T.emerald}20`}}><p style={{fontSize:11,fontWeight:700,color:T.t400,textTransform:"uppercase",marginBottom:4}}>Risk Assessment</p><div style={{display:"flex",gap:20}}><div><p style={{fontSize:10,color:T.t400}}>Category</p><p style={{fontSize:14,fontWeight:700,color:T.emerald}}>Low Risk</p></div><div><p style={{fontSize:10,color:T.t400}}>Score</p><p style={{fontSize:14,fontWeight:700}}>120/1000</p></div><div><p style={{fontSize:10,color:T.t400}}>Action</p><p style={{fontSize:14,fontWeight:700,color:T.emerald}}>APPROVE</p></div></div></div><div style={{marginTop:12}}><div style={{display:"flex",justifyContent:"space-between"}}><span style={{fontSize:11,fontWeight:700,color:T.t400,textTransform:"uppercase"}}>Flagged Rules</span><Badge text="Transaction Approved" color={T.emerald}/></div><p style={{fontSize:20,fontWeight:800,marginTop:4}}>0/7</p></div></>)
          )}
        </div>
      </div>
    </div>);

    /* FRM ALERTS */
    if(page==="frm"&&frmSub==="alerts"){
      if(alertView){const aa=alertActions[alertView.id];return(<div>
        <button onClick={()=>{setAlertView(null);setAlertTab("details");}} style={{display:"flex",alignItems:"center",gap:4,background:"none",border:"none",color:T.t400,fontSize:12,cursor:"pointer",marginBottom:12,fontFamily:T.sans}}><ArrowLeft size={14}/>Back to Alerts</button>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><h2 style={{fontSize:18,fontWeight:700}}>Alert Details</h2><div style={{display:"flex",gap:6}}><button onClick={()=>setModal("escalate")} style={{display:"flex",alignItems:"center",gap:4,padding:"7px 14px",borderRadius:6,background:T.white,color:T.t700,border:`1px solid ${T.border}`,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}><ArrowUpRight size={13}/>Escalate</button><button onClick={()=>setModal("investigate")} style={{display:"flex",alignItems:"center",gap:4,padding:"7px 14px",borderRadius:6,background:T.white,color:T.t700,border:`1px solid ${T.border}`,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}><Eye size={13}/>Investigate</button></div></div>
        <div style={{display:"grid",gridTemplateColumns:"300px 1fr",gap:16}}>
          <div style={{background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`}}>
            <p style={{fontSize:15,fontWeight:700}}>{alertView.rule}</p><p style={{fontSize:10,color:T.t400}}>{alertView.time}</p>
            <div style={{display:"flex",gap:4,margin:"8px 0"}}><Badge text={aa==="confirmed"?"Confirmed Fraud":aa==="fp"?"False Positive":`${alertView.risk} Risk`} color={aa==="confirmed"?T.rose:aa==="fp"?T.amber:riskColor(alertView.risk)}/><Badge text={aa==="confirmed"?"Resolved":aa==="fp"?"Resolved":alertView.status} color={aa?"resolved"?T.emerald:T.amber:T.amber}/></div>
            <div style={{display:"flex",gap:6,margin:"12px 0"}}><button onClick={()=>setAlertActions(p=>({...p,[alertView.id]:"fp"}))} style={{flex:1,padding:"7px 0",borderRadius:6,background:aa==="fp"?T.amberBg:T.roseBg,color:aa==="fp"?T.amber:T.rose,border:aa==="fp"?`2px solid ${T.amber}`:"none",fontSize:10,fontWeight:700,cursor:"pointer",fontFamily:T.sans}}>⚠ False Positive</button><button onClick={()=>setAlertActions(p=>({...p,[alertView.id]:"confirmed"}))} style={{flex:1,padding:"7px 0",borderRadius:6,background:aa==="confirmed"?T.roseBg:T.emeraldBg,color:aa==="confirmed"?T.rose:T.emerald,border:aa==="confirmed"?`2px solid ${T.rose}`:"none",fontSize:10,fontWeight:700,cursor:"pointer",fontFamily:T.sans}}>✓ Confirm Fraud</button></div>
            {aa&&<p style={{fontSize:10,fontWeight:600,color:aa==="confirmed"?T.rose:T.amber,textAlign:"center",marginBottom:8}}>Marked as {aa==="confirmed"?"Confirmed Fraud":"False Positive"}</p>}
            {[{l:"Alert ID",v:alertView.id},{l:"Transaction ID",v:alertView.txnId.slice(0,24)},{l:"Amount",v:alertView.amount},{l:"Score",v:alertView.score},{l:"Priority",v:alertView.risk==="High"?"HIGH":"LOW"},{l:"Group",v:alertView.group},{l:"Customer",v:alertView.user},{l:"Merchant",v:alertView.merchant}].map((f,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"6px 0",borderBottom:i<7?`1px solid ${T.borderLight}`:"none"}}><span style={{fontSize:10,color:T.t400}}>{f.l}</span><span style={{fontSize:10,fontWeight:600}}>{f.v}</span></div>)}
          </div>
          <div>
            <div style={{display:"flex",gap:8,marginBottom:16,borderBottom:`1px solid ${T.border}`}}>{["details","history"].map(t=><button key={t} onClick={()=>setAlertTab(t)} style={{padding:"8px 16px",fontSize:12,fontWeight:alertTab===t?700:500,color:alertTab===t?T.primary:T.t400,background:"none",border:"none",borderBottom:alertTab===t?`2px solid ${T.primary}`:"2px solid transparent",cursor:"pointer",fontFamily:T.sans}}>{t==="details"?"Transaction Details":"Assignment History"}</button>)}</div>
            {alertTab==="details"&&<div>
              <ExpandSection title="Transaction"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,paddingTop:10}}>{[{l:"Transaction ID",v:alertView.txnId.slice(0,24)},{l:"Date & Time",v:new Date().toISOString()},{l:"Amount",v:alertView.amount},{l:"Currency",v:alertView.currency},{l:"Event Type",v:alertView.evType},{l:"Event Subtype",v:alertView.evSub},{l:"Channel",v:alertView.channel},{l:"Transaction Status",v:alertView.txnStatus},{l:"Risk Assessment",v:alertView.risk}].map((f,i)=><div key={i}><p style={{fontSize:9,color:T.t400}}>{f.l}</p><p style={{fontSize:11,fontWeight:600}}>{f.v}</p></div>)}</div></ExpandSection>
              {alertView.payMethod==="CARD"&&<ExpandSection title="Origin"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,paddingTop:10}}>{[{l:"Payment Method",v:alertView.payMethod},{l:"Card Balance",v:alertView.cardBal},{l:"Card Token",v:"tok_kfi5mrmX"},{l:"Card Status",v:"ACTIVE"},{l:"Card Number",v:alertView.cardNum},{l:"Card Type",v:"CREDIT"},{l:"Authenticated",v:"true"},{l:"Authorized",v:"true"},{l:"Tokenized",v:"true"},{l:"Merchant Name",v:alertView.merchant},{l:"Category Code",v:"5411"},{l:"Device Risk Score",v:"N/A"},{l:"SIM Swap Detected",v:"false"},{l:"Behavioral Score",v:"N/A"}].map((f,i)=><div key={i}><p style={{fontSize:9,color:T.t400}}>{f.l}</p><p style={{fontSize:11,fontWeight:600}}>{f.v}</p></div>)}</div></ExpandSection>}
              <ExpandSection title="Geographic"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,paddingTop:10}}>{[{l:"IP Address",v:"103.21.58.194"},{l:"Country",v:"India"},{l:"City",v:"Mumbai"},{l:"ISP",v:"Reliance Jio"},{l:"VPN Detected",v:"false"},{l:"Proxy Detected",v:"false"}].map((f,i)=><div key={i}><p style={{fontSize:9,color:T.t400}}>{f.l}</p><p style={{fontSize:11,fontWeight:600}}>{f.v}</p></div>)}</div></ExpandSection>
              <ExpandSection title="User Info"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,paddingTop:10}}>{[{l:"Customer ID",v:"cust_VeYsy7Kh"},{l:"Name",v:alertView.user},{l:"Phone",v:"+91 9856773220"},{l:"Email",v:"user@gmail.com"},{l:"KYC Status",v:"Verified"},{l:"Account Age",v:"2 years"}].map((f,i)=><div key={i}><p style={{fontSize:9,color:T.t400}}>{f.l}</p><p style={{fontSize:11,fontWeight:600}}>{f.v}</p></div>)}</div></ExpandSection>
              <ExpandSection title="Profile Updates"><div style={{paddingTop:10}}><p style={{fontSize:11,color:T.t400}}>No recent profile changes detected</p></div></ExpandSection>
              <ExpandSection title="Security"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,paddingTop:10}}>{[{l:"MFA Enabled",v:"true"},{l:"Last Password Change",v:"45 days ago"},{l:"Failed Logins (24h)",v:"0"},{l:"Active Sessions",v:"2"},{l:"Trusted Device",v:"true"}].map((f,i)=><div key={i}><p style={{fontSize:9,color:T.t400}}>{f.l}</p><p style={{fontSize:11,fontWeight:600}}>{f.v}</p></div>)}</div></ExpandSection>
              <ExpandSection title="Banking"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10,paddingTop:10}}>{[{l:"Bank Name",v:"HDFC Bank"},{l:"Account Type",v:"Savings"},{l:"IFSC",v:"HDFC0001234"},{l:"Account Age",v:"4 years"}].map((f,i)=><div key={i}><p style={{fontSize:9,color:T.t400}}>{f.l}</p><p style={{fontSize:11,fontWeight:600}}>{f.v}</p></div>)}</div></ExpandSection>
              <ExpandSection title="Destination"><div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10,paddingTop:10}}>{[{l:"Beneficiary Name",v:"Unknown"},{l:"Beneficiary Bank",v:alertView.merchant},{l:"Country",v:"India"},{l:"New Beneficiary",v:"false"}].map((f,i)=><div key={i}><p style={{fontSize:9,color:T.t400}}>{f.l}</p><p style={{fontSize:11,fontWeight:600}}>{f.v}</p></div>)}</div></ExpandSection>
            </div>}
            {alertTab==="history"&&<div style={{background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`}}>
              <div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div style={{display:"flex",alignItems:"center",gap:6}}><RefreshCw size={14} color={T.t400}/><div><p style={{fontSize:14,fontWeight:700}}>Assignment History</p><p style={{fontSize:10,color:T.t400}}>Track all reassignments and escalations</p></div></div><Badge text="1 Assignment" color={T.primary}/></div>
              <div style={{background:T.roseBg,borderRadius:10,padding:14,border:`1px dashed ${T.rose}40`}}>
                <div style={{display:"flex",alignItems:"center",gap:6,marginBottom:8}}><Badge text="Escalated" color={T.rose}/><span style={{fontSize:11,fontWeight:600,color:T.t500}}>#1</span><span style={{fontSize:10,color:T.t400,marginLeft:"auto"}}>{dateStr} at {time}</span></div>
                <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:10}}><div><p style={{fontSize:9,color:T.t400}}>FROM</p><p style={{fontSize:11,fontWeight:600}}>Yash Gajra</p></div><div><p style={{fontSize:9,color:T.t400}}>TO</p><p style={{fontSize:11,fontWeight:600,color:T.primary}}>Aarti Borse</p></div><div><p style={{fontSize:9,color:T.t400}}>ASSIGNED BY</p><p style={{fontSize:11,fontWeight:600}}>Yash Gajra</p></div></div>
                <div style={{marginTop:8,padding:"6px 10px",borderRadius:6,background:T.roseBg,border:`1px dashed ${T.rose}30`}}><p style={{fontSize:10,color:T.rose}}>ESCALATED: High risk transaction requires L2 review</p></div>
              </div>
            </div>}
          </div>
        </div>
      </div>);}
      return(<div>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><div style={{display:"flex",gap:8}}><span style={{fontSize:12,fontWeight:600,color:T.t400,padding:"6px 0"}}>Quick Filters:</span>{[{l:"High Risk",n:frmAlerts.filter(a=>a.risk==="High").length,c:T.rose},{l:"Medium",n:frmAlerts.filter(a=>a.risk==="Medium").length,c:T.amber},{l:"Low Risk",n:frmAlerts.filter(a=>a.risk==="Low").length,c:T.emerald}].map((f,i)=><span key={i} style={{fontSize:11,padding:"4px 12px",borderRadius:99,border:`1px solid ${f.c}`,color:f.c,fontWeight:600}}>{f.l} ({f.n})</span>)}</div></div>
        <div style={{display:"flex",gap:16}}>
          <div style={{flex:1}}>{frmAlerts.map(a=>{const aa=alertActions[a.id];return(<div key={a.id} onClick={()=>setSelAlert(selAlert?.id===a.id?null:a)} style={{background:selAlert?.id===a.id?T.primaryBg:T.white,borderRadius:10,padding:14,border:`1px solid ${selAlert?.id===a.id?T.primary+"40":T.border}`,marginBottom:8,cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:13,fontWeight:700}}>{a.rule}</span><div style={{display:"flex",gap:4}}><Badge text={aa==="confirmed"?"Confirmed Fraud":aa==="fp"?"False Positive":`${a.risk} Risk`} color={aa==="confirmed"?T.rose:aa==="fp"?T.amber:riskColor(a.risk)}/><Badge text={aa?"Resolved":a.status} color={aa?T.emerald:a.status==="Escalated"?T.rose:T.amber}/></div></div><div style={{display:"flex",gap:16,fontSize:11,color:T.t500}}><span>Amount: <strong style={{color:T.t900}}>{a.amount}</strong></span><span>User: <strong style={{color:T.t900}}>{a.user}</strong></span><span>Score: <strong style={{color:T.t900}}>{a.score}/1000</strong></span></div><p style={{fontSize:10,color:T.t400,marginTop:4}}>{a.time}</p></div>);})}</div>
          {selAlert&&<div style={{width:340,background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`,position:"sticky",top:20,alignSelf:"flex-start"}}>
            <div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontSize:14,fontWeight:700}}>Alert Summary</span><div style={{display:"flex",gap:4}}><button onClick={()=>{setAlertView(selAlert);setSelAlert(null);}} style={{fontSize:10,padding:"4px 10px",borderRadius:6,background:T.primaryBg,color:T.primary,border:"none",fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>View Details</button><X size={14} color={T.t400} style={{cursor:"pointer"}} onClick={()=>setSelAlert(null)}/></div></div>
            <p style={{fontSize:13,fontWeight:700}}>{selAlert.rule}</p><p style={{fontSize:10,color:T.t400}}>{selAlert.time}</p>
            <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:6,marginTop:10}}>{[{l:"Amount",v:selAlert.amount},{l:"User",v:selAlert.user},{l:"Score",v:`${selAlert.score}/1000`},{l:"Channel",v:selAlert.channel}].map((d,i)=><div key={i}><p style={{fontSize:9,color:T.t400}}>{d.l}</p><p style={{fontSize:10,fontWeight:600}}>{d.v}</p></div>)}</div>
            <div style={{display:"flex",gap:6,marginTop:12}}><button onClick={()=>{setAlertActions(p=>({...p,[selAlert.id]:"fp"}));}} style={{flex:1,padding:7,borderRadius:6,background:alertActions[selAlert.id]==="fp"?T.amberBg:T.roseBg,color:alertActions[selAlert.id]==="fp"?T.amber:T.rose,border:alertActions[selAlert.id]==="fp"?`2px solid ${T.amber}`:"none",fontSize:10,fontWeight:700,cursor:"pointer",fontFamily:T.sans}}>⚠ False Positive</button><button onClick={()=>{setAlertActions(p=>({...p,[selAlert.id]:"confirmed"}));}} style={{flex:1,padding:7,borderRadius:6,background:alertActions[selAlert.id]==="confirmed"?T.roseBg:T.emeraldBg,color:alertActions[selAlert.id]==="confirmed"?T.rose:T.emerald,border:alertActions[selAlert.id]==="confirmed"?`2px solid ${T.rose}`:"none",fontSize:10,fontWeight:700,cursor:"pointer",fontFamily:T.sans}}>✓ Confirm Fraud</button></div>
            <div style={{display:"flex",gap:6,marginTop:6}}><button onClick={()=>setModal("escalate")} style={{flex:1,padding:7,borderRadius:6,background:T.bg,color:T.t700,border:`1px solid ${T.border}`,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>Escalate</button><button onClick={()=>setModal("investigate")} style={{flex:1,padding:7,borderRadius:6,background:T.bg,color:T.t700,border:`1px solid ${T.border}`,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>Investigate</button></div>
          </div>}
        </div>
      </div>);
    }

    /* FRM LISTS */
    if(page==="frm"&&frmSub==="lists"){
      if(createList)return(<div>
        <button onClick={()=>setCreateList(false)} style={{display:"flex",alignItems:"center",gap:4,background:"none",border:"none",color:T.t400,fontSize:12,cursor:"pointer",marginBottom:12,fontFamily:T.sans}}><ArrowLeft size={14}/>Back to Lists</button>
        <h2 style={{fontSize:20,fontWeight:700,marginBottom:16}}>Create New List</h2>
        <p style={{fontSize:12,color:T.t400,marginBottom:20}}>Upload a CSV file to create a new list for fraud detection.</p>
        <div style={{maxWidth:700}}>
          <div style={{marginBottom:20}}><label style={{fontSize:14,fontWeight:700,display:"block",marginBottom:6}}>List Name</label><input placeholder="e.g., blacklisted_ips, suspicious_users" style={{width:"100%",padding:"10px 14px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:13,fontFamily:T.sans}}/><p style={{fontSize:11,color:T.t400,marginTop:4}}>Use a descriptive name for your list</p></div>
          <div style={{marginBottom:20}}><label style={{fontSize:14,fontWeight:700,display:"block",marginBottom:6}}>CSV File</label><div style={{border:`2px dashed ${T.border}`,borderRadius:10,padding:30,textAlign:"center"}}><Download size={24} color={T.t300} style={{margin:"0 auto"}}/><p style={{fontSize:12,color:T.t400,marginTop:8}}>Upload a single-column CSV file with a title in the first row</p><button style={{padding:"8px 16px",borderRadius:6,background:T.bg,border:`1px solid ${T.border}`,fontSize:12,fontWeight:600,cursor:"pointer",marginTop:8,fontFamily:T.sans}}>Choose File</button></div><p style={{fontSize:11,color:T.t400,marginTop:4}}>The CSV should contain a single column of values (e.g., IP addresses, user IDs, etc.)</p></div>
          <div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><button onClick={()=>setCreateList(false)} style={{padding:"10px 16px",borderRadius:8,background:T.bg,color:T.t700,border:`1px solid ${T.border}`,fontSize:13,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>Cancel</button><button onClick={()=>setCreateList(false)} style={{padding:"10px 24px",borderRadius:8,background:T.primary,color:"#fff",border:"none",fontSize:13,fontWeight:700,cursor:"pointer",fontFamily:T.sans}}>Create List</button></div>
        </div>
      </div>);
      if(viewList)return(<div>
        <button onClick={()=>setViewList(null)} style={{display:"flex",alignItems:"center",gap:4,background:"none",border:"none",color:T.t400,fontSize:12,cursor:"pointer",marginBottom:12,fontFamily:T.sans}}><ArrowLeft size={14}/>Back to Lists</button>
        <h2 style={{fontSize:18,fontWeight:700,marginBottom:16}}>List: {viewList}</h2>
        <div style={{background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`}}>
          <div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{fontSize:13,fontWeight:700}}>Entries</span><button style={{display:"flex",alignItems:"center",gap:4,padding:"6px 12px",borderRadius:6,background:T.primary,color:"#fff",border:"none",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}><Plus size={12}/>Add Entry</button></div>
          {Array.from({length:5}).map((_,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"8px 0",borderBottom:i<4?`1px solid ${T.borderLight}`:"none"}}><span style={{fontSize:12,fontFamily:T.mono,color:T.t700}}>{viewList.includes("ip")?`192.168.${Math.floor(Math.random()*255)}.${Math.floor(Math.random()*255)}`:viewList.includes("device")?`dev_${Math.random().toString(36).slice(2,10)}`:`usr_${Math.random().toString(36).slice(2,10)}`}</span><button style={{fontSize:10,color:T.rose,background:"none",border:"none",cursor:"pointer",fontFamily:T.sans}}>Remove</button></div>)}
        </div>
      </div>);
      return(<div>
        <div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><div><h2 style={{fontSize:18,fontWeight:700}}>Lists</h2><p style={{fontSize:12,color:T.t400}}>Manage blocklists and watchlists</p></div><button onClick={()=>setCreateList(true)} style={{display:"flex",alignItems:"center",gap:6,padding:"8px 16px",borderRadius:8,background:T.primary,color:"#fff",border:"none",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}><Plus size={14}/>Create List</button></div>
        {["blacklisted_ips","suspicious_users","blocked_devices","high_risk_merchants","sanctioned_entities"].map((l,i)=>(<div key={i} style={{background:T.white,borderRadius:10,padding:14,border:`1px solid ${T.border}`,marginBottom:8,display:"flex",justifyContent:"space-between",alignItems:"center"}}><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:36,height:36,borderRadius:8,background:T.primaryBg,display:"flex",alignItems:"center",justifyContent:"center"}}><Database size={16} color={T.primary}/></div><div><p style={{fontSize:13,fontWeight:700}}>{l}</p><p style={{fontSize:10,color:T.t400}}>{Math.floor(Math.random()*500+50)} entries · Updated {Math.floor(Math.random()*24+1)}h ago</p></div></div><div style={{display:"flex",gap:6}}><button onClick={()=>setViewList(l)} style={{padding:"6px 12px",borderRadius:6,background:T.bg,color:T.t500,border:`1px solid ${T.border}`,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>View</button><button onClick={()=>setViewList(l)} style={{padding:"6px 12px",borderRadius:6,background:T.bg,color:T.t500,border:`1px solid ${T.border}`,fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>Edit</button><button style={{padding:"6px 12px",borderRadius:6,background:T.roseBg,color:T.rose,border:"none",fontSize:10,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>Delete</button></div></div>))}
      </div>);
    }

    /* FRM REPORTS */
    if(page==="frm"&&frmSub==="reports")return(<div>
      <div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><h2 style={{fontSize:18,fontWeight:700}}>Reports</h2><div style={{display:"flex",gap:6}}><button onClick={csvDownload} style={{display:"flex",alignItems:"center",gap:4,padding:"6px 12px",borderRadius:6,background:T.bg,border:`1px solid ${T.border}`,fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}><Download size={13}/>Download CSV</button><button style={{display:"flex",alignItems:"center",gap:4,padding:"6px 12px",borderRadius:6,background:T.primary,color:"#fff",border:"none",fontSize:11,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}><RefreshCw size={13}/>Generate</button></div></div>
      <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:16}}><Stat label="Alerts Today" value="41" delta="+12%"/><Stat label="Amount Saved" value="$750K" delta="+8%"/><Stat label="Resolution Rate" value="4.9%"/><Stat label="Avg Response" value="8.4 hrs"/></div>
      <div style={{background:T.white,borderRadius:10,border:`1px solid ${T.border}`,overflow:"hidden",marginBottom:16}}>
        <div style={{padding:"14px 16px",borderBottom:`1px solid ${T.border}`,display:"flex",justifyContent:"space-between"}}><span style={{fontSize:13,fontWeight:700}}>Rule Performance Report</span><span style={{fontSize:10,color:T.t400}}>Generated {dateStr} {time}</span></div>
        <table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{background:T.bg}}>{["ID","Rule Name","Channel","Event","Status","Priority","Score","Alerts","Confirmed","False Pos"].map(h=><th key={h} style={{padding:"8px 12px",textAlign:"left",fontWeight:600,color:T.t400,fontSize:9,textTransform:"uppercase"}}>{h}</th>)}</tr></thead>
        <tbody>{frmRules.slice(0,8).map(r=><tr key={r.id} style={{borderBottom:`1px solid ${T.borderLight}`}}><td style={{padding:"8px 12px",fontWeight:600}}>{r.id}</td><td style={{padding:"8px 12px"}}>{r.name}</td><td style={{padding:"8px 12px",color:T.t400}}>{r.ch||"—"}</td><td style={{padding:"8px 12px"}}>{r.type}</td><td style={{padding:"8px 12px"}}><Badge text={r.st} color={T.emerald}/></td><td style={{padding:"8px 12px"}}><Badge text={r.pri} color={r.pri==="High"?T.rose:T.emerald}/></td><td style={{padding:"8px 12px",fontWeight:600}}>{r.score}</td><td style={{padding:"8px 12px"}}>{r.alerts}</td><td style={{padding:"8px 12px"}}>{Math.floor(r.alerts*0.6)}</td><td style={{padding:"8px 12px",color:T.rose}}>{r.fp}</td></tr>)}</tbody></table>
      </div>
      <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
        <div style={{background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`}}><p style={{fontSize:13,fontWeight:700,marginBottom:12}}>Recent Alert Activity</p>{[{l:"Confirm Fraud",d:"Confirmed cases",n:1,c:T.rose},{l:"False Positive",d:"Incorrectly flagged",n:1,c:T.amber},{l:"Pending Review",d:"Awaiting analyst",n:39,c:T.blue},{l:"Auto-Resolved",d:"System resolved",n:0,c:T.emerald}].map((a,i)=><div key={i} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderBottom:i<3?`1px solid ${T.borderLight}`:"none"}}><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:"50%",background:a.c}}/><div><p style={{fontSize:12,fontWeight:600}}>{a.l}</p><p style={{fontSize:10,color:T.t400}}>{a.d}</p></div></div><p style={{fontSize:12,fontWeight:700}}>{a.n}</p></div>)}</div>
        <div style={{background:T.white,borderRadius:10,padding:16,border:`1px solid ${T.border}`}}><p style={{fontSize:13,fontWeight:700,marginBottom:12}}>Performance</p>{[{l:"Investigation",v:"2.4%",c:T.blue},{l:"False Positive Rate",v:"2.4%",c:T.rose},{l:"Productivity",v:"4.9%",c:T.emerald}].map((m,i)=><div key={i} style={{padding:"10px 0",borderBottom:i<2?`1px solid ${T.borderLight}`:"none"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:12,fontWeight:600}}>{m.l}</span><span style={{fontSize:16,fontWeight:800,color:m.c}}>{m.v}</span></div><div style={{height:4,background:T.borderLight,borderRadius:2,marginTop:4}}><div style={{height:"100%",background:m.c,borderRadius:2,width:m.v}}/></div></div>)}</div>
      </div>
    </div>);
    return null;
  };

  return(
    <div style={{fontFamily:T.sans,minHeight:"100vh",display:"flex",background:T.bg,WebkitFontSmoothing:"antialiased"}}>
      <div style={{width:sideOpen?240:64,background:T.white,borderRight:`1px solid ${T.border}`,display:"flex",flexDirection:"column",transition:"width 0.2s",flexShrink:0,overflow:"hidden"}}>
        <a href="/" style={{padding:sideOpen?"16px 18px":"16px 14px",borderBottom:`1px solid ${T.borderLight}`,display:"flex",alignItems:"center",gap:8,cursor:"pointer",textDecoration:"none"}}><img src={BUREAU_LOGO} alt="Bureau" style={{height:sideOpen?36:28,width:"auto",flexShrink:0}}/></a>
        <div style={{flex:1,padding:"8px 0",overflowY:"auto"}}>
          {navItems.map(n=>(<div key={n.id}><div onClick={()=>{if(n.id==="frm"&&page==="frm"){setFrmOpen(!frmOpen);return;}setPage(n.id);if(n.sub){setFrmSub(n.sub[0].id);setFrmOpen(true);}setCreateRule(false);setEditRule(null);setAlertView(null);setSelAlert(null);setCreateList(false);setViewList(null);}} style={{display:"flex",alignItems:"center",gap:10,padding:sideOpen?"9px 18px":"9px 20px",cursor:"pointer",background:page===n.id?T.primaryBg:"transparent",color:page===n.id?T.primary:T.t500,borderRight:page===n.id?`2px solid ${T.primary}`:"none",transition:"all 0.15s"}}><n.icon size={18} style={{flexShrink:0}}/>{sideOpen&&<span style={{fontSize:13,fontWeight:page===n.id?600:500,whiteSpace:"nowrap"}}>{n.label}</span>}{sideOpen&&n.sub&&(frmOpen&&page===n.id?<ChevronUp size={14} style={{marginLeft:"auto"}}/>:<ChevronDown size={14} style={{marginLeft:"auto"}}/>)}</div>
            {n.sub&&page===n.id&&sideOpen&&frmOpen&&<div style={{paddingLeft:46,marginTop:4}}>{n.sub.map(s=><div key={s.id} onClick={(e)=>{e.stopPropagation();setFrmSub(s.id);setAlertView(null);setSelAlert(null);setCreateRule(false);setEditRule(null);setCreateList(false);setViewList(null);}} style={{padding:"6px 12px",fontSize:12,cursor:"pointer",color:frmSub===s.id?T.primary:T.t400,fontWeight:frmSub===s.id?600:400,background:frmSub===s.id?T.primaryBg:"transparent",borderRadius:6,marginBottom:2}}>{s.label}</div>)}</div>}
          </div>))}
        </div>
        <div style={{borderTop:`1px solid ${T.borderLight}`,padding:sideOpen?"12px 18px":"12px 14px"}}>
          {sideOpen&&<div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><div style={{width:28,height:28,borderRadius:"50%",background:T.primary,display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,color:"#fff"}}>YG</div><div><p style={{fontSize:11,fontWeight:600}}>Yash Gajra</p><p style={{fontSize:9,color:T.t400}}>yash.gajra@bureau.id</p></div></div>}
          <div style={{display:"flex",gap:6}}><button onClick={()=>setSideOpen(!sideOpen)} style={{flex:1,padding:"6px 0",borderRadius:6,background:T.bg,color:T.t500,border:`1px solid ${T.border}`,fontSize:10,fontWeight:600,cursor:"pointer",display:"flex",alignItems:"center",justifyContent:"center",gap:4,fontFamily:T.sans}}>{sideOpen?<><ChevronLeft size={12}/>Collapse</>:<Menu size={14}/>}</button>{sideOpen&&<button onClick={()=>setAuth(false)} style={{padding:"6px 10px",borderRadius:6,background:T.roseBg,color:T.rose,border:"none",fontSize:10,fontWeight:600,cursor:"pointer",display:"flex",alignItems:"center",gap:4,fontFamily:T.sans}}><LogOut size={12}/>Logout</button>}</div>
        </div>
      </div>
      <div style={{flex:1,display:"flex",flexDirection:"column",overflow:"hidden"}}>
        <header style={{height:52,background:T.white,borderBottom:`1px solid ${T.border}`,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 20px",flexShrink:0}}>
          <p style={{fontSize:14,fontWeight:700}}>{page==="dashboard"?"Dashboard":page==="workflows"?"Workflows":page==="profiles"?"Profiles":page==="frm"?(alertView?`Alerts › Alert #${alertView.id}`:editRule?`Rules › ${editRule.name}`:createRule?"Rules › Create New":createList?"Lists › Create New":viewList?`Lists › ${viewList}`:`Transaction Monitoring › ${frmSub.charAt(0).toUpperCase()+frmSub.slice(1)}`):""}</p>
          <div style={{display:"flex",alignItems:"center",gap:12}}>
            <div style={{display:"flex",alignItems:"center",gap:6,fontSize:11,color:T.t400}}><span style={{width:6,height:6,borderRadius:"50%",background:T.emerald,display:"inline-block"}}/>{rm.flag} {rm.country} · <span style={{fontFamily:T.mono,fontSize:10}}>{time}</span></div>
            <div style={{width:1,height:20,background:T.border}}/>
            <a href="/" style={{display:"flex",alignItems:"center",gap:4,fontSize:11,color:T.primary,fontWeight:600,textDecoration:"none"}}><ExternalLink size={12}/>Main Site</a>
          </div>
        </header>
        <div style={{flex:1,padding:20,overflowY:"auto"}}>{renderPage()}</div>
      </div>
      {modal==="escalate"&&<Modal title="Escalate Alert" onClose={()=>setModal(null)}>
        <p style={{fontSize:12,color:T.t400,marginBottom:16}}>Escalate this alert to a supervisor for review.</p>
        <div style={{marginBottom:12}}><label style={{fontSize:11,fontWeight:600,display:"block",marginBottom:4}}>Escalate to Supervisor</label><select style={{width:"100%",padding:"10px 12px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:12,fontFamily:T.sans}}><option>Select a supervisor...</option><option>Aarti Borse — Risk Analyst</option><option>Himanshu Yadav — Compliance Lead</option><option>Kritika — Account Manager</option><option>Nagmanjunath — Business Lead</option></select></div>
        <div style={{marginBottom:16}}><label style={{fontSize:11,fontWeight:600,display:"block",marginBottom:4}}>Escalation Reason</label><textarea style={{width:"100%",padding:"10px 12px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:12,fontFamily:T.sans,height:80,resize:"none"}} placeholder="Enter reason for escalation..."/></div>
        <div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><button onClick={()=>setModal(null)} style={{padding:"8px 16px",borderRadius:8,background:T.bg,color:T.t700,border:`1px solid ${T.border}`,fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>Cancel</button><button onClick={()=>setModal(null)} style={{padding:"8px 16px",borderRadius:8,background:T.primary,color:"#fff",border:"none",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>Escalate Alert</button></div>
      </Modal>}
      {modal==="investigate"&&<Modal title="Investigate Alert" onClose={()=>setModal(null)}>
        <p style={{fontSize:12,color:T.t400,marginBottom:16}}>Begin detailed investigation process for this alert.</p>
        <div style={{marginBottom:12}}><label style={{fontSize:11,fontWeight:600,display:"block",marginBottom:4}}>Assign to User</label><select style={{width:"100%",padding:"10px 12px",borderRadius:8,border:`1.5px solid ${T.border}`,fontSize:12,fontFamily:T.sans}}><option>No assignment</option><option>Yash Gajra</option><option>Aarti Borse</option><option>Kritika</option><option>Naman Jain</option></select></div>
        <div style={{marginBottom:12}}><label style={{fontSize:11,fontWeight:600,display:"block",marginBottom:4}}>Investigation Priority</label><div style={{display:"flex",gap:12}}>{["High","Medium","Low"].map(p=><label key={p} style={{display:"flex",alignItems:"center",gap:4,fontSize:12,cursor:"pointer"}}><input type="radio" name="priority" defaultChecked={p==="Low"}/>{p}</label>)}</div></div>
        <div style={{padding:"10px 12px",borderRadius:8,background:T.blueBg,border:`1px solid ${T.blue}20`,marginBottom:16}}><p style={{fontSize:11,color:T.blue}}>Transaction data loaded and will be included as evidence</p></div>
        <div style={{display:"flex",gap:8,justifyContent:"flex-end"}}><button onClick={()=>setModal(null)} style={{padding:"8px 16px",borderRadius:8,background:T.bg,color:T.t700,border:`1px solid ${T.border}`,fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>Cancel</button><button onClick={()=>setModal(null)} style={{padding:"8px 16px",borderRadius:8,background:T.primary,color:"#fff",border:"none",fontSize:12,fontWeight:600,cursor:"pointer",fontFamily:T.sans}}>Start Investigation</button></div>
      </Modal>}
      <style>{`@import url('https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700;9..40,800&family=JetBrains+Mono:wght@400;500;600&display=swap');*{box-sizing:border-box;margin:0;}::-webkit-scrollbar{width:5px;}::-webkit-scrollbar-thumb{background:${T.border};border-radius:3px;}select,textarea,input{outline:none;}`}</style>
    </div>
  );
}

export default function BureauPlatformV2() {
  return (
    <Suspense fallback={<div style={{ minHeight: "100vh", background: "#f8fafc", display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ width: 32, height: 32, border: "3px solid #e2e8f0", borderTopColor: "#253B80", borderRadius: "50%", animation: "spin 1s linear infinite" }} /><style>{`@keyframes spin { to { transform: rotate(360deg); } }`}</style></div>}>
      <BureauPlatformV2Inner />
    </Suspense>
  );
}
